"""Default initial state dict for CSOD LangGraph runs."""
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional


def create_csod_initial_state(
    user_query: str,
    session_id: str,
    active_project_id: Optional[str] = None,
    selected_data_sources: Optional[List[Any]] = None,
    compliance_profile: Optional[Dict[str, Any]] = None,
    silver_gold_tables_only: bool = False,
    generate_sql: bool = False,
    causal_graph_enabled: bool = False,
    causal_vertical: str = "lms",
) -> dict:
    """Build an initial state dict for the CSOD workflow."""
    return {
        "user_query": user_query,
        "session_id": session_id or str(uuid.uuid4()),
        "messages": [],
        "created_at": datetime.utcnow(),
        "selected_data_sources": selected_data_sources or [],
        "compliance_profile": compliance_profile or {},
        "active_project_id": active_project_id or "",
        "controls": [],
        "risks": [],
        "scenarios": [],
        "test_cases": [],
        "siem_rules": [],
        "playbooks": [],
        "test_scripts": [],
        "data_pipelines": [],
        "dashboards": [],
        "vulnerability_mappings": [],
        "gap_analysis_results": [],
        "cross_framework_mappings": [],
        "metrics_context": [],
        "xsoar_indicators": [],
        "resolved_metrics": [],
        "resolved_focus_areas": [],
        "focus_area_categories": [],
        "execution_steps": [],
        "csod_intent": None,
        "csod_persona": None,
        "csod_plan_summary": None,
        "csod_estimated_complexity": None,
        "csod_execution_plan": [],
        "csod_gap_notes": [],
        "csod_data_sources_in_scope": [],
        "csod_resolved_schemas": [],
        "csod_gold_standard_tables": [],
        "csod_retrieved_metrics": [],
        "csod_retrieved_kpis": [],
        "csod_scored_context": None,
        "csod_dropped_items": [],
        "csod_schema_gaps": [],
        "csod_scoring_threshold_applied": 0.5,
        "csod_metric_recommendations": [],
        "csod_kpi_recommendations": [],
        "csod_table_recommendations": [],
        "csod_data_science_insights": [],
        "csod_medallion_plan": {},
        "csod_unmeasured_requirements": [],
        "csod_generate_sql": generate_sql,
        "csod_generated_gold_model_sql": [],
        "csod_gold_model_artifact_name": None,
        "csod_dashboard_assembled": None,
        "csod_test_cases": [],
        "csod_test_queries": [],
        "csod_test_validation_passed": False,
        "csod_test_validation_failures": [],
        "csod_schedule_type": None,
        "csod_schedule_config": {},
        "csod_execution_frequency": None,
        "csod_validation_iteration": 0,
        "csod_metric_validation_passed": False,
        "csod_metric_validation_failures": [],
        "csod_metric_validation_warnings": [],
        "csod_assembled_output": None,
        "csod_use_decision_tree": False,
        "csod_causal_graph_enabled": causal_graph_enabled,
        "csod_causal_nodes": [],
        "csod_causal_edges": [],
        "csod_causal_graph_metadata": None,
        "csod_causal_retrieval_stats": None,
        "csod_causal_metric_registry": [],
        "causal_vertical": causal_vertical,
        "cce_db_url": None,
        "current_step_index": 0,
        "plan_completion_status": {},
        "context_cache": {},
        "iteration_count": 0,
        "max_iterations": 3,
        "validation_results": [],
        "refinement_history": [],
        "data_enrichment": {
            "needs_mdl": True,
            "needs_metrics": True,
            "suggested_focus_areas": [],
            "metrics_intent": "current_state",
        },
        "silver_gold_tables_only": silver_gold_tables_only,
        "output_format": "cubejs",
        "cubejs_schema_files": [],
        "cubejs_generation_errors": [],
    }
