"""Data science insights enricher — DEPRECATED.

Insights are now generated inline by csod_metrics_recommender_node.
This node is kept as a passthrough for backward compatibility with
the monolithic graph.
"""
import logging

from app.agents.csod.csod_nodes._helpers import CSOD_State, _csod_log_step, logger

_deprecation_logged = False

def csod_data_science_insights_enricher_node(state: CSOD_State) -> CSOD_State:
    """Deprecated passthrough — insights are now generated by the metrics recommender."""
    global _deprecation_logged
    if not _deprecation_logged:
        logger.warning(
            "csod_data_science_insights_enricher_node is deprecated; "
            "insights are now generated inline by csod_metrics_recommender_node."
        )
        _deprecation_logged = True

    state.setdefault("csod_data_science_insights", [])

    _csod_log_step(
        state, "csod_data_science_insights_enricher", "csod_data_science_insights_enricher",
        inputs={"deprecated": True},
        outputs={"insights_count": len(state.get("csod_data_science_insights", []))},
    )

    return state
