OPPORTUNITY_TABLE_SCHEMA_PROMPT = """
{{
  "table": "salesforce_opportunities",
  "columns": [
    {{"name": "id", "type": "text"}},
    {{"name": "is_deleted", "type": "boolean"}},
    {{"name": "account_id", "type": "text"}},
    {{"name": "record_type_id", "type": "text"}},
    {{"name": "name", "type": "text"}},
    {{"name": "description", "type": "text"}},
    {{"name": "stage_name", "type": "text"}},
    {{"name": "amount", "type": "double precision"}},
    {{"name": "probability", "type": "double precision"}},
    {{"name": "close_date", "type": "text"}},
    {{"name": "type", "type": "text"}},
    {{"name": "next_step", "type": "text"}},
    {{"name": "lead_source", "type": "text"}},
    {{"name": "is_closed", "type": "boolean"}},
    {{"name": "is_won", "type": "boolean"}},
    {{"name": "forecast_category", "type": "text"}},
    {{"name": "forecast_category_name", "type": "text"}},
    {{"name": "campaign_id", "type": "text"}},
    {{"name": "has_opportunity_line_item", "type": "boolean"}},
    {{"name": "pricebook2_id", "type": "text"}},
    {{"name": "owner_id", "type": "text"}},
    {{"name": "created_date", "type": "text"}},
    {{"name": "createddate_year", "type": "bigint"}},
    {{"name": "created_by_id", "type": "text"}},
    {{"name": "last_modified_date", "type": "text"}},
    {{"name": "last_modified_by_id", "type": "text"}},
    {{"name": "system_modstamp", "type": "text"}},
    {{"name": "last_activity_date", "type": "text"}},
    {{"name": "fiscal_quarter", "type": "bigint"}},
    {{"name": "fiscal_year", "type": "bigint"}},
    {{"name": "fiscal", "type": "text"}},
    {{"name": "last_viewed_date", "type": "text"}},
    {{"name": "last_referenced_date", "type": "text"}},
    {{"name": "synced_quote_id", "type": "double precision"}},
    {{"name": "has_open_activity", "type": "boolean"}},
    {{"name": "has_overdue_task", "type": "boolean"}},
    {{"name": "contract_term", "type": "text"}},
    {{"name": "progress_towards_technical_win", "type": "text"}},
    {{"name": "second_demo_completed", "type": "text"}},
    {{"name": "demo_scheduled", "type": "text"}},
    {{"name": "loss_reason", "type": "text"}},
    {{"name": "sub_lead_source", "type": "text"}},
    {{"name": "demo_completed", "type": "text"}},
    {{"name": "discovery_completed", "type": "text"}},
    {{"name": "timeline_budget_confirmed", "type": "text"}},
    {{"name": "current_tech_stack", "type": "text"}},
    {{"name": "mutual_action_plan", "type": "text"}},
    {{"name": "next_steps_in_receiving_technical_win", "type": "text"}},
    {{"name": "poc_completed", "type": "text"}},
    {{"name": "risk_mitigation", "type": "text"}},
    {{"name": "opportunity_notes", "type": "text"}},
    {{"name": "campaign_type_for_opp__c", "type": "text"}},
    {{"name": "campaign_name_for_opp__c", "type": "text"}},
    {{"name": "communication_channel_for_opp__c", "type": "text"}},
    {{"name": "lead_source_2__c", "type": "text"}},
    {{"name": "value_category__c", "type": "text"}},
    {{"name": "use_case_category__c", "type": "text"}},
    {{"name": "inbound_v_outbound__c", "type": "text"}},
    {{"name": "current_state_for_example_facts_as_well__c", "type": "text"}},
    {{"name": "lid__linkedin_company_id__c", "type": "double precision"}},
    {{"name": "se_owner__c", "type": "text"}},
    {{"name": "poc_start_date__c", "type": "text"}},
    {{"name": "x6sense_account_fit_at_opportunity_creat__c", "type": "text"}},
    {{"name": "x6sense_buying_stage_at_opportunity_crea__c", "type": "text"}},
    {{"name": "quarterly_deal_status__c", "type": "text"}},
    {{"name": "renewal_type__c", "type": "text"}},
    {{"name": "pain_points__c", "type": "text"}},
    {{"name": "loss_reason_details__c", "type": "text"}},
    {{"name": "objectives__c", "type": "text"}},
    {{"name": "key_highlights__c", "type": "text"}},
    {{"name": "installation__c", "type": "text"}},
    {{"name": "vp_grade__c", "type": "text"}},
    {{"name": "deal_profile__c", "type": "text"}},
    {{"name": "business_unit__c", "type": "text"}},
    {{"name": "modules_used__c", "type": "text"}},
    {{"name": "license_start_date__c", "type": "text"}},
    {{"name": "license_end_date__c", "type": "text"}},
    {{"name": "color_notes__c", "type": "text"}},
    {{"name": "pov_owner__c", "type": "text"}},
    {{"name": "demo_completed_on__c", "type": "text"}},
    {{"name": "business_value__c", "type": "text"}},
    {{"name": "nrr__c", "type": "double precision"}},
    {{"name": "pandadoc__trackingnumber__c", "type": "double precision"}},
    {{"name": "active_opportunity__c", "type": "boolean"}},
    {{"name": "software_arr", "type": "double precision"}},
    {{"name": "services_arr", "type": "double precision"}},
    {{"name": "spuns__c", "type": "text"}},
    {{"name": "pov_in_progress__c", "type": "boolean"}},
    {{"name": "how_did_you_hear_about_us__c", "type": "text"}},
    {{"name": "nrr_pilot_non_recurring_revenue__c", "type": "double precision"}},
    {{"name": "arr_hosting__c", "type": "double precision"}},
    {{"name": "total_arr_-_validated", "type": "bigint"}},
    {{"name": "tcv_total_contract_value1__c", "type": "bigint"}},
    {{"name": "activity_last_week__c", "type": "text"}},
    {{"name": "arr_monthly__c", "type": "bigint"}},
    {{"name": "benefits__c", "type": "text"}},
    {{"name": "pilot_term__c", "type": "double precision"}},
    {{"name": "mrr_total__c", "type": "double precision"}},
    {{"name": "purchase_order__c", "type": "text"}},
    {{"name": "competitor__c", "type": "text"}},
    {{"name": "customer_health__c", "type": "text"}},
    {{"name": "lost_to__c", "type": "text"}},
    {{"name": "use_cases_in_production__c", "type": "text"}},
    {{"name": "csm__c", "type": "text"}},
    {{"name": "sdr__c", "type": "text"}},
    {{"name": "meddicc__c", "type": "text"}},
    {{"name": "date_entered_s0", "type": "text"}},
    {{"name": "buyer_persona__c", "type": "text"}},
    {{"name": "annualized_pilot__c", "type": "double precision"}},
    {{"name": "server_units__c", "type": "text"}},
    {{"name": "date_entered_s1", "type": "text"}},
    {{"name": "services_sold__c", "type": "text"}},
    {{"name": "date_entered_s3", "type": "text"}},
    {{"name": "launch_use_case__c", "type": "text"}},
    {{"name": "why_tellius__c", "type": "text"}},
    {{"name": "potential_roadblocks__c", "type": "text"}},
    {{"name": "agreement_type__c", "type": "text"}},
    {{"name": "product_issues_requests__c", "type": "text"}},
    {{"name": "engagement_phase__c", "type": "text"}},
    {{"name": "nda_cda_required__c", "type": "text"}},
    {{"name": "date_entered_s4", "type": "text"}},
    {{"name": "vendor_system__c", "type": "text"}},
    {{"name": "date_entered_s5", "type": "text"}},
    {{"name": "date_entered_s6", "type": "text"}},
    {{"name": "date_entered_closed_won__c", "type": "text"}},
    {{"name": "date_entered_closed_lost__c", "type": "text"}},
    {{"name": "days_in_qualification__c", "type": "double precision"}},
    {{"name": "days_in_discovery__c", "type": "double precision"}},
    {{"name": "days_in_diagnose__c", "type": "double precision"}},
    {{"name": "next_step_new__c", "type": "text"}},
    {{"name": "security_review__c", "type": "text"}},
    {{"name": "days_in_prove_value__c", "type": "double precision"}},
    {{"name": "tech_success_criteria__c", "type": "text"}},
    {{"name": "days_in_proposal__c", "type": "double precision"}},
    {{"name": "days_in_contract_legal_review__c", "type": "double precision"}},
    {{"name": "tech_completion_actual__c", "type": "text"}},
    {{"name": "arr__c", "type": "double precision"}},
    {{"name": "tech_next_steps__c", "type": "text"}},
    {{"name": "opp_csid__c", "type": "text"}},
    {{"name": "dashboardsgsp__amount_won__c", "type": "double precision"}},
    {{"name": "dashboardsgsp__close_date_extensions__c", "type": "double precision"}},
    {{"name": "dashboardsgsp__close_date_month_extensions__c", "type": "double precision"}},
    {{"name": "dashboardsgsp__date_opportunity_was_closed__c", "type": "text"}},
    {{"name": "dashboardsgsp__days_open_delete__c", "type": "double precision"}},
    {{"name": "dashboardsgsp__last_stage_change_date__c", "type": "text"}},
    {{"name": "dashboardsgsp__days_open__c", "type": "double precision"}},
    {{"name": "tech_win__c", "type": "boolean"}},
    {{"name": "dashboardsgsp__days_since_last_stage_change__c", "type": "double precision"}},
    {{"name": "closed_lost_reason__c", "type": "text"}},
    {{"name": "closed_lost_details__c", "type": "text"}},
    {{"name": "toggle__c", "type": "boolean"}},
    {{"name": "incumbent__c", "type": "double precision"}},
    {{"name": "competition__c", "type": "double precision"}},
    {{"name": "incumbent_notes__c", "type": "text"}},
    {{"name": "competition_notes__c", "type": "text"}},
    {{"name": "pricing_notes__c", "type": "text"}},
    {{"name": "timeline_notes__c", "type": "text"}},
    {{"name": "new_expand_min__c", "type": "double precision"}},
    {{"name": "new_expand_max__c", "type": "double precision"}},
    {{"name": "primary_use_case_notes__c", "type": "text"}},
    {{"name": "primary_use_case__c", "type": "double precision"}},
    {{"name": "tier_1_pharma_life_sciences__c", "type": "boolean"}},
    {{"name": "services__c", "type": "double precision"}},
    {{"name": "new_expand_arr_likely__c", "type": "double precision"}},
    {{"name": "opportunity_setter__c", "type": "text"}},
    {{"name": "ae", "type": "text"}},
    {{"name": "compelling_mechanism__c", "type": "text"}},
    {{"name": "next_step_date__c", "type": "text"}},
    {{"name": "next_step_owner__c", "type": "text"}},
    {{"name": "customer_health_account__c", "type": "text"}},
    {{"name": "risks_plan__c", "type": "text"}},
    {{"name": "opportunity_source_category__c", "type": "text"}},
    {{"name": "snapshot_bifurcation_id__c", "type": "double precision"}},
    {{"name": "clp_use_case_dev_end__c", "type": "text"}},
    {{"name": "clp_executive_review_start__c", "type": "text"}},
    {{"name": "clp_confirm_budget_end__c", "type": "text"}},
    {{"name": "clp_proposal_order_form_end__c", "type": "text"}},
    {{"name": "clp_it_security_review_end__c", "type": "text"}},
    {{"name": "clp_proposal_order_form_start__c", "type": "text"}},
    {{"name": "clp_it_security_review_start__c", "type": "text"}},
    {{"name": "clp_executive_review_end__c", "type": "text"}},
    {{"name": "clp_use_case_dev_start__c", "type": "text"}},
    {{"name": "clp_user_showcase_end__c", "type": "text"}},
    {{"name": "clp_user_showcase_start__c", "type": "text"}},
    {{"name": "clp_build_business_value_deck_end__c", "type": "text"}},
    {{"name": "clp_build_business_value_deck_start__c", "type": "text"}},
    {{"name": "clp_identify_data_cap_users_end__c", "type": "text"}},
    {{"name": "clp_identify_data_cap_users_start__c", "type": "text"}},
    {{"name": "clp_confirm_budget_start__c", "type": "text"}},
    {{"name": "clp_discovery_interviews_end_user_end__c", "type": "text"}},
    {{"name": "clp_discovery_interviews_end_user_start__c", "type": "text"}},
    {{"name": "clp_discovery_interviews_analytics_start__c", "type": "text"}},
    {{"name": "clp_discovery_interviews_analytics_end__c", "type": "text"}},
    {{"name": "clp_contract_nego_start__c", "type": "text"}},
    {{"name": "clp_contract_nego_end__c", "type": "text"}},
    {{"name": "clp_pov_plan_start__c", "type": "text"}},
    {{"name": "clp_define_competitive_posit_start__c", "type": "text"}},
    {{"name": "clp_pov_plan_end__c", "type": "text"}},
    {{"name": "clp_define_competitive_posit_end__c", "type": "text"}},
    {{"name": "clp_build_business_value_deck_status__c", "type": "text"}},
    {{"name": "clp_confirm_budget_and_eb_status__c", "type": "text"}},
    {{"name": "clp_contract_nego_and_sign_status__c", "type": "text"}},
    {{"name": "clp_define_comp_positioning_status__c", "type": "text"}},
    {{"name": "clp_disc_interviews_w_analytics_status__c", "type": "text"}},
    {{"name": "clp_disc_interviews_w_end_users_status__c", "type": "text"}},
    {{"name": "clp_executive_review_status__c", "type": "text"}},
    {{"name": "clp_identify_data_capacity_status__c", "type": "text"}},
    {{"name": "clp_it_security_review_status__c", "type": "text"}},
    {{"name": "clp_pov_plan_success_criteria_status__c", "type": "text"}},
    {{"name": "proposal_order_form_status__c", "type": "text"}},
    {{"name": "clp_use_case_development_status__c", "type": "text"}},
    {{"name": "clp_user_showcase_and_feedback_status__c", "type": "text"}},
    {{"name": "close_plan_last_updated__c", "type": "text"}},
    {{"name": "gong__gong_count__c", "type": "double precision"}},
    {{"name": "gong__maincompetitors__c", "type": "double precision"}},
    {{"name": "opportunity_count__c", "type": "double precision"}},
    {{"name": "clp_confirm_budget_and_eb_status1__c", "type": "text"}},
    {{"name": "clp_technical_evaluation_details__c", "type": "text"}},
    {{"name": "clp_business_case_details__c", "type": "double precision"}},
    {{"name": "clp_procurement_it_details__c", "type": "double precision"}},
    {{"name": "x202407_closed_lost_campaign_inclusion__c", "type": "boolean"}},
    {{"name": "x202407_closed_lost_inclusion_reason__c", "type": "double precision"}},
    {{"name": "dayssincelastactivity__c", "type": "double precision"}},
    {{"name": "next_step_history__c", "type": "text"}},
    {{"name": "dsla_toggle__c", "type": "boolean"}},
    {{"name": "last_activity_date_display__c", "type": "text"}},
    {{"name": "closedlost__c", "type": "boolean"}},
    {{"name": "next_step_last_updated__c", "type": "text"}},
    {{"name": "days_since_next_step_updated__c", "type": "double precision"}},
    {{"name": "sybill_champion__c", "type": "text"}},
    {{"name": "sybill_compelling_event__c", "type": "text"}},
    {{"name": "sybill_decision_maker__c", "type": "text"}},
    {{"name": "sybill_decision_process__c", "type": "text"}},
    {{"name": "sybill_economic_buyer__c", "type": "text"}},
    {{"name": "sybill_identify_pain__c", "type": "text"}},
    {{"name": "sybill_metrics__c", "type": "text"}},
    {{"name": "sybill_paper_process__c", "type": "text"}},
    {{"name": "next_step_changed__c", "type": "boolean"}},
    {{"name": "leader_notes_changed__c", "type": "boolean"}},
    {{"name": "disco_current_state__c", "type": "text"}},
    {{"name": "disco_why_anything__c", "type": "text"}},
    {{"name": "disco_why_now__c", "type": "text"}},
    {{"name": "disco_why_tellius__c", "type": "text"}},
    {{"name": "expected_pov_start_date__c", "type": "text"}},
    {{"name": "first_meeting_status__c", "type": "text"}},
    {{"name": "pov_type__c", "type": "double precision"}},
    {{"name": "plan_aligned_on_involvement__c", "type": "boolean"}},
    {{"name": "plan_executive_alignment_completed__c", "type": "boolean"}},
    {{"name": "plan_leadership_signoff__c", "type": "boolean"}},
    {{"name": "plan_path_to_purchase__c", "type": "boolean"}},
    {{"name": "plan_production_timeline_defined__c", "type": "boolean"}},
    {{"name": "plan_resource_commitment__c", "type": "boolean"}},
    {{"name": "plan_risk_mitigation__c", "type": "text"}},
    {{"name": "plan_success_criteria_timeline__c", "type": "boolean"}},
    {{"name": "plan_use_case_linked__c", "type": "boolean"}},
    {{"name": "qual_authority__c", "type": "boolean"}},
    {{"name": "qual_maturity__c", "type": "boolean"}},
    {{"name": "qual_need__c", "type": "boolean"}},
    {{"name": "qualification_notes__c", "type": "text"}},
    {{"name": "when_is_budget_submitted__c", "type": "double precision"}},
    {{"name": "when_is_fiscal_year_end__c", "type": "double precision"}},
    {{"name": "exec_presentation_deck_link__c", "type": "double precision"}},
    {{"name": "date_entered_s2", "type": "text"}},
    {{"name": "arr_won__c", "type": "double precision"}},
    {{"name": "activity_count_events__c", "type": "double precision"}},
    {{"name": "fq4_cl_campaign_owner__c", "type": "double precision"}}
  ]
}}
"""
 

TASK_TABLE_SCHEMA_PROMPT = """
{{
  "table": "salesforce_tasks",
  "columns": [
    {{"name": "Id", "type": "String"}},
    {{"name": "WhoId", "type": "String"}},
    {{"name": "WhatId", "type": "String"}},
    {{"name": "Subject", "type": "String"}},
    {{"name": "ActivityDate", "type": "Date"}},
    {{"name": "Status", "type": "String"}},
    {{"name": "Priority", "type": "String"}},
    {{"name": "Description", "type": "String"}},
    {{"name": "OwnerId", "type": "String"}},
    {{"name": "IsClosed", "type": "Boolean"}},
    {{"name": "IsDeleted", "type": "Boolean"}},
    {{"name": "ActivityType", "type": "String"}},
    {{"name": "CallDisposition", "type": "String"}},
    {{"name": "CallDurationInSeconds", "type": "Integer"}},
    {{"name": "TaskSubtype", "type": "String"}},
    {{"name": "ReminderDateTime", "type": "Datetime"}},
    {{"name": "IsReminderSet", "type": "Boolean"}},
    {{"name": "RecurrenceActivityId", "type": "String"}},
    {{"name": "RecurrenceStartDateOnly", "type": "Date"}},
    {{"name": "RecurrenceEndDateOnly", "type": "Date"}},
    {{"name": "RecurrenceTimeZoneSidKey", "type": "String"}},
    {{"name": "RecurrenceType", "type": "String"}},
    {{"name": "RecurrenceInterval", "type": "Integer"}},
    {{"name": "RecurrenceDayOfWeekMask", "type": "Integer"}},
    {{"name": "RecurrenceDayOfMonth", "type": "Integer"}},
    {{"name": "RecurrenceInstance", "type": "String"}},
    {{"name": "RecurrenceMonthOfYear", "type": "String"}},
    {{"name": "IsArchived", "type": "Boolean"}},
    {{"name": "IsHighPriority", "type": "Boolean"}}
  ]
}}
"""

ACCOUNT_TABLE_SCHEMA_PROMPT = """
{{
  "table": "salesforce_accounts",
  "columns": [
    {{"name": "id", "type": "text"}},
    {{"name": "is_deleted", "type": "boolean"}},
    {{"name": "master_record_id", "type": "double precision"}},
    {{"name": "name", "type": "text"}},
    {{"name": "type", "type": "text"}},
    {{"name": "parent_id", "type": "text"}},
    {{"name": "billing_street", "type": "text"}},
    {{"name": "billing_city", "type": "text"}},
    {{"name": "billing_state", "type": "text"}},
    {{"name": "billing_postal_code", "type": "text"}},
    {{"name": "billing_country", "type": "text"}},
    {{"name": "billing_latitude", "type": "double precision"}},
    {{"name": "billing_longitude", "type": "double precision"}},
    {{"name": "billing_geocode_accuracy", "type": "double precision"}},
    {{"name": "billing_address", "type": "text"}},
    {{"name": "shipping_street", "type": "text"}},
    {{"name": "shipping_city", "type": "text"}},
    {{"name": "shipping_state", "type": "text"}},
    {{"name": "shipping_postal_code", "type": "text"}},
    {{"name": "shipping_country", "type": "text"}},
    {{"name": "shipping_latitude", "type": "double precision"}},
    {{"name": "shipping_longitude", "type": "double precision"}},
    {{"name": "shipping_geocode_accuracy", "type": "double precision"}},
    {{"name": "shipping_address", "type": "text"}},
    {{"name": "phone", "type": "text"}},
    {{"name": "website", "type": "text"}},
    {{"name": "photo_url", "type": "text"}},
    {{"name": "industry", "type": "text"}},
    {{"name": "annual_revenue", "type": "double precision"}},
    {{"name": "number_of_employees", "type": "double precision"}},
    {{"name": "description", "type": "text"}},
    {{"name": "owner_id", "type": "text"}},
    {{"name": "created_date", "type": "text"}},
    {{"name": "created_by_id", "type": "text"}},
    {{"name": "last_modified_date", "type": "text"}},
    {{"name": "last_modified_by_id", "type": "text"}},
    {{"name": "system_modstamp", "type": "text"}},
    {{"name": "last_activity_date", "type": "text"}},
    {{"name": "last_viewed_date", "type": "text"}},
    {{"name": "last_referenced_date", "type": "text"}},
    {{"name": "jigsaw_company_id", "type": "double precision"}},
    {{"name": "market_segment", "type": "text"}},
    {{"name": "total_opportunity_count", "type": "double precision"}},
    {{"name": "describe", "type": "double precision"}},
    {{"name": "test_currency", "type": "double precision"}},
    {{"name": "customer_health", "type": "text"}},
    {{"name": "industry_summary", "type": "text"}},
    {{"name": "sales_region", "type": "text"}},
    {{"name": "company_revenue", "type": "text"}},
    {{"name": "customer_success_manager", "type": "double precision"}},
    {{"name": "touchpoint_frequency", "type": "text"}},
    {{"name": "account_status", "type": "text"}},
    {{"name": "linkedin_account_url", "type": "text"}},
    {{"name": "account_score", "type": "text"}},
    {{"name": "territory", "type": "text"}},
    {{"name": "revenue", "type": "text"}},
    {{"name": "disable_duplicate_check", "type": "boolean"}},
    {{"name": "dc3_index", "type": "double precision"}},
    {{"name": "active_client", "type": "boolean"}},
    {{"name": "engagement_phase", "type": "text"}},
    {{"name": "csm", "type": "text"}},
    {{"name": "success_criteria", "type": "text"}},
    {{"name": "business_value_impact", "type": "text"}},
    {{"name": "weekly_key_highlights", "type": "text"}},
    {{"name": "benefits", "type": "text"}},
    {{"name": "objectives", "type": "text"}},
    {{"name": "bdr", "type": "text"}},
    {{"name": "use_cases_in_production", "type": "text"}},
    {{"name": "pain_points", "type": "text"}},
    {{"name": "bdr_working", "type": "boolean"}},
    {{"name": "milestone_status", "type": "text"}},
    {{"name": "milestone_status_notes", "type": "text"}},
    {{"name": "health_rationale", "type": "text"}},
    {{"name": "health_conversion_plan", "type": "text"}},
    {{"name": "next_steps", "type": "text"}},
    {{"name": "value_category", "type": "text"}},
    {{"name": "business_value_roi_health", "type": "text"}},
    {{"name": "champion_health", "type": "text"}},
    {{"name": "company_dynamics_health", "type": "text"}},
    {{"name": "sponsorship_health", "type": "text"}},
    {{"name": "adoption_usage_health", "type": "text"}},
    {{"name": "use_case_category", "type": "text"}},
    {{"name": "number_of_use_cases_in_production", "type": "double precision"}},
    {{"name": "use_cases_in_implementation", "type": "text"}},
    {{"name": "use_cases_in_backlog", "type": "text"}},
    {{"name": "notion_link", "type": "text"}},
    {{"name": "next_renewal_date", "type": "text"}},
    {{"name": "days_until_next_renewal", "type": "double precision"}},
    {{"name": "historical_health_rationale", "type": "text"}},
    {{"name": "kickoff_date", "type": "text"}},
    {{"name": "installation_completed_date", "type": "text"}},
    {{"name": "installation_target_date", "type": "text"}},
    {{"name": "data_loaded_date", "type": "text"}},
    {{"name": "data_loaded_target_date", "type": "text"}},
    {{"name": "use_case_executed_date", "type": "text"}},
    {{"name": "use_case_target_execution_date", "type": "text"}},
    {{"name": "first_value_delivered_date", "type": "text"}},
    {{"name": "first_value_delivered_target_date", "type": "text"}},
    {{"name": "end_users_enabled_date", "type": "text"}},
    {{"name": "end_users_enabled_target_date", "type": "text"}},
    {{"name": "kickoff_target_date", "type": "text"}},
    {{"name": "lead_se", "type": "text"}},
    {{"name": "sales_summary", "type": "text"}},
    {{"name": "tier", "type": "text"}},
    {{"name": "pendo_usage_trending", "type": "double precision"}},
    {{"name": "pendo_time_on_site", "type": "double precision"}},
    {{"name": "pendo_visitors", "type": "double precision"}},
    {{"name": "assigned_elt_member", "type": "text"}},
    {{"name": "current_tech_stack", "type": "text"}},
    {{"name": "total_arr", "type": "double precision"}},
    {{"name": "active_arr", "type": "double precision"}},
    {{"name": "recent_conversion_hubspot", "type": "text"}},
    {{"name": "qualified_signals_engagement_trend", "type": "text"}},
    {{"name": "qualified_signals_engagement_intent", "type": "text"}},
    {{"name": "qualified_signals_active_session_time", "type": "double precision"}},
    {{"name": "recent_conversion_date_hubspot", "type": "text"}},
    {{"name": "number_of_form_submissions_hubspot", "type": "double precision"}},
    {{"name": "qualified_signals_score", "type": "double precision"}},
    {{"name": "qualified_signals_session_count", "type": "double precision"}},
    {{"name": "qualified_signals_visitor_count", "type": "double precision"}},
    {{"name": "time_last_seen_hubspot", "type": "text"}},
    {{"name": "budget_finalization_date", "type": "text"}},
    {{"name": "account_name_for_pendo", "type": "text"}},
    {{"name": "email_campaign_permissions", "type": "text"}},
    {{"name": "open_opportunity_count", "type": "double precision"}},
    {{"name": "x6s_revenue_range", "type": "double precision"}},
    {{"name": "x6s_industry", "type": "text"}},
    {{"name": "x6s_employee_range", "type": "double precision"}},
    {{"name": "x6s_segment_names", "type": "text"}},
    {{"name": "x6s_naics_code", "type": "double precision"}},
    {{"name": "x6s_estimated_revenue", "type": "double precision"}},
    {{"name": "x6s_employee_count_estimate", "type": "double precision"}},
    {{"name": "x6s_primary_industry_1", "type": "double precision"}},
    {{"name": "x6s_primary_industry_2", "type": "double precision"}},
    {{"name": "x6s_primary_industry_3", "type": "double precision"}},
    {{"name": "x6s_account_buying_stage", "type": "text"}},
    {{"name": "x6s_account_intent_score", "type": "double precision"}},
    {{"name": "x6s_account_profile", "type": "text"}},
    {{"name": "x6s_account_profile_score", "type": "double precision"}},
    {{"name": "x6s_account_reach_score", "type": "text"}},
    {{"name": "x6s_account_6qa", "type": "double precision"}},
    {{"name": "x6s_account_6qa_start_date", "type": "text"}},
    {{"name": "x6s_account_6qa_end_date", "type": "text"}},
    {{"name": "x6s_account_6qa_age_in_days", "type": "double precision"}},
    {{"name": "x6s_account_numerical_reach_score", "type": "double precision"}},
    {{"name": "x6s_account_scores_last_updated", "type": "text"}},
    {{"name": "linkedin_company_id", "type": "double precision"}},
    {{"name": "account_csid", "type": "text"}},
    {{"name": "attending_gartner_d&a_2024", "type": "boolean"}},
    {{"name": "top_100_pharma", "type": "boolean"}},
    {{"name": "domain", "type": "text"}},
    {{"name": "account_owned_by_active_ae", "type": "boolean"}},
    {{"name": "gong_count", "type": "double precision"}},
    {{"name": "2024_reassignment", "type": "text"}},
    {{"name": "top_100_cpg", "type": "boolean"}},
    {{"name": "account_owner_name", "type": "text"}},
    {{"name": "next_step_changed", "type": "boolean"}},
    {{"name": "next_steps_last_updated", "type": "text"}},
    {{"name": "zoominfo_enrich_status", "type": "double precision"}},
    {{"name": "zoominfo_first_updated", "type": "text"}},
    {{"name": "zoominfo_id", "type": "double precision"}},
    {{"name": "zoominfo_inboxai_id", "type": "double precision"}},
    {{"name": "zoominfo_last_updated", "type": "text"}},
    {{"name": "zi_primary_industry", "type": "text"}},
    {{"name": "zi_sub_industry", "type": "text"}},
    {{"name": "notion__c", "type": "boolean"}}
  ]
}}
"""
CONTACT_TABLE_SCHEMA_PROMPT = """{
  "name": "salesforce_contacts",
  "fields": [
    {{"name": "Id", "type": "String"}},
    {{"name": "IsDeleted", "type": "Boolean"}},
    {{"name": "MasterRecordId", "type": "String"}},
    {{"name": "AccountId", "type": "String"}},
    {{"name": "LastName", "type": "String"}},
    {{"name": "FirstName", "type": "String"}},
    {{"name": "Salutation", "type": "String"}},
    {{"name": "Name", "type": "String"}},
    {{"name": "OtherStreet", "type": "String"}},
    {{"name": "OtherCity", "type": "String"}},
    {{"name": "OtherState", "type": "String"}},
    {{"name": "OtherPostalCode", "type": "String"}},
    {{"name": "OtherCountry", "type": "String"}},
    {{"name": "OtherLatitude", "type": "Double"}},
    {{"name": "OtherLongitude", "type": "Double"}},
    {{"name": "OtherGeocodeAccuracy", "type": "String"}},
    {{"name": "OtherAddress", "type": "String"}},
    {{"name": "MailingStreet", "type": "String"}},
    {{"name": "MailingCity", "type": "String"}},
    {{"name": "MailingState", "type": "String"}},
    {{"name": "MailingPostalCode", "type": "String"}},
    {{"name": "MailingCountry", "type": "String"}},
    {{"name": "MailingLatitude", "type": "Double"}},
    {{"name": "MailingLongitude", "type": "Double"}},
    {{"name": "MailingGeocodeAccuracy", "type": "String"}},
    {{"name": "MailingAddress", "type": "String"}},
    {{"name": "Phone", "type": "String"}},
    {{"name": "Fax", "type": "String"}},
    {{"name": "MobilePhone", "type": "String"}},
    {{"name": "HomePhone", "type": "String"}},
    {{"name": "OtherPhone", "type": "String"}},
    {{"name": "AssistantPhone", "type": "String"}},
    {{"name": "ReportsToId", "type": "String"}},
    {{"name": "Email", "type": "String"}},
    {{"name": "Title", "type": "String"}},
    {{"name": "Department", "type": "String"}},
    {{"name": "AssistantName", "type": "String"}},
    {{"name": "LeadSource", "type": "String"}},
    {{"name": "Birthdate", "type": "Date"}},
    {{"name": "Description", "type": "String"}},
    {{"name": "OwnerId", "type": "String"}},
    {{"name": "LastActivityDate", "type": "Date"}},
    {{"name": "LastCURequestDate", "type": "Datetime"}},
    {{"name": "LastCUUpdateDate", "type": "Datetime"}},
    {{"name": "LastViewedDate", "type": "Datetime"}},
    {{"name": "LastReferencedDate", "type": "Datetime"}},
    {{"name": "EmailBouncedReason", "type": "String"}},
    {{"name": "EmailBouncedDate", "type": "Datetime"}},
    {{"name": "IsEmailBounced", "type": "Boolean"}},
    {{"name": "PhotoUrl", "type": "String"}},
    {{"name": "Jigsaw", "type": "String"}},
    {{"name": "JigsawContactId", "type": "String"}},
    {{"name": "CleanStatus", "type": "String"}},
    {{"name": "Level__c", "type": "String"}},
    {{"name": "Languages__c", "type": "String"}}
  ]
}}
"""
LEAD_TABLE_SCHEMA_PROMPT = """
{
  "name": "salesforce_leads",
  "fields": [
    {{"name": "Id", "type": "String"}},
    {{"name": "IsDeleted", "type": "Boolean"}},
    {{"name": "MasterRecordId", "type": "String"}},
    {{"name": "LastName", "type": "String"}},
    {{"name": "FirstName", "type": "String"}},
    {{"name": "Salutation", "type": "String"}},
    {{"name": "Name", "type": "String"}},
    {{"name": "Title", "type": "String"}},
    {{"name": "Company", "type": "String"}},
    {{"name": "Street", "type": "String"}},
    {{"name": "City", "type": "String"}},
    {{"name": "State", "type": "String"}},
    {{"name": "PostalCode", "type": "String"}},
    {{"name": "Country", "type": "String"}},
    {{"name": "Latitude", "type": "Double"}},
    {{"name": "Longitude", "type": "Double"}},
    {{"name": "GeocodeAccuracy", "type": "String"}},
    {{"name": "Address", "type": "String"}},
    {{"name": "Phone", "type": "String"}},
    {{"name": "MobilePhone", "type": "String"}},
    {{"name": "Fax", "type": "String"}},
    {{"name": "Email", "type": "String"}},
    {{"name": "Website", "type": "String"}},
    {{"name": "PhotoUrl", "type": "String"}},
    {{"name": "Description", "type": "String"}},
    {{"name": "LeadSource", "type": "String"}},
    {{"name": "Status", "type": "String"}},
    {{"name": "Industry", "type": "String"}},
    {{"name": "Rating", "type": "String"}},
    {{"name": "AnnualRevenue", "type": "Double"}},
    {{"name": "NumberOfEmployees", "type": "Integer"}},
    {{"name": "OwnerId", "type": "String"}},
    {{"name": "IsConverted", "type": "Boolean"}},
    {{"name": "ConvertedDate", "type": "Date"}},
    {{"name": "ConvertedAccountId", "type": "String"}},
    {{"name": "ConvertedContactId", "type": "String"}},
    {{"name": "ConvertedOpportunityId", "type": "String"}},
    {{"name": "IsUnreadByOwner", "type": "Boolean"}},
    {{"name": "LastActivityDate", "type": "Date"}},
    {{"name": "LastViewedDate", "type": "Datetime"}},
    {{"name": "LastReferencedDate", "type": "Datetime"}},
    {{"name": "Jigsaw", "type": "String"}},
    {{"name": "JigsawContactId", "type": "String"}},
    {{"name": "CleanStatus", "type": "String"}},
    {{"name": "CompanyDunsNumber", "type": "String"}},
    {{"name": "DandbCompanyId", "type": "String"}},
    {{"name": "EmailBouncedReason", "type": "String"}},
    {{"name": "EmailBouncedDate", "type": "Datetime"}},
    {{"name": "IndividualId", "type": "String"}},
    {{"name": "SICCode__c", "type": "String"}},
    {{"name": "ProductInterest__c", "type": "String"}},
    {{"name": "Primary__c", "type": "String"}},
    {{"name": "CurrentGenerators__c", "type": "String"}},
    {{"name": "NumberofLocations__c", "type": "Double"}}
  ]
}
"""

CAMPAIGN_TABLE_SCHEMA_PROMPT = """
{{
  "table": "salesforce_campaigns",
  "columns": [
    {{"name": "Id", "type": "String"}},
    {{"name": "IsDeleted", "type": "Boolean"}},
    {{"name": "Name", "type": "String"}},
    {{"name": "ParentId", "type": "String"}},
    {{"name": "Type", "type": "String"}},
    {{"name": "Status", "type": "String"}},
    {{"name": "StartDate", "type": "Date"}},
    {{"name": "EndDate", "type": "Date"}},
    {{"name": "ExpectedRevenue", "type": "Double"}},
    {{"name": "BudgetedCost", "type": "Double"}},
    {{"name": "ActualCost", "type": "Double"}},
    {{"name": "ExpectedResponse", "type": "Double"}},
    {{"name": "NumberSent", "type": "Double"}},
    {{"name": "IsActive", "type": "Boolean"}},
    {{"name": "Description", "type": "String"}},
    {{"name": "NumberOfLeads", "type": "Integer"}},
    {{"name": "NumberOfConvertedLeads", "type": "Integer"}},
    {{"name": "NumberOfContacts", "type": "Integer"}},
    {{"name": "NumberOfResponses", "type": "Integer"}},
    {{"name": "NumberOfOpportunities", "type": "Integer"}},
    {{"name": "NumberOfWonOpportunities", "type": "Integer"}},
    {{"name": "AmountAllOpportunities", "type": "Double"}},
    {{"name": "AmountWonOpportunities", "type": "Double"}},
    {{"name": "OwnerId", "type": "String"}},
    {{"name": "LastActivityDate", "type": "Date"}},
    {{"name": "LastViewedDate", "type": "Datetime"}},
    {{"name": "LastReferencedDate", "type": "Datetime"}},
    {{"name": "CampaignMemberRecordTypeId", "type": "String"}},
    {{"name": "CurrencyIsoCode", "type": "String"}},
    {{"name": "NumberOfWonOpportunities__c", "type": "Double"}},
    {{"name": "AmountWonOpportunities__c", "type": "Double"}}
  ]
}}
"""

USER_TABLE_SCHEMA_PROMPT = """
{{
  "table": "salesforce_users",
  "columns": [
    {{"name": "Id", "type": "String"}},
    {{"name": "Username", "type": "String"}},
    {{"name": "LastName", "type": "String"}},
    {{"name": "FirstName", "type": "String"}},
    {{"name": "Name", "type": "String"}},
    {{"name": "CompanyName", "type": "String"}},
    {{"name": "Division", "type": "String"}},
    {{"name": "Department", "type": "String"}},
    {{"name": "Title", "type": "String"}},
    {{"name": "Street", "type": "String"}},
    {{"name": "City", "type": "String"}},
    {{"name": "State", "type": "String"}},
    {{"name": "PostalCode", "type": "String"}},
    {{"name": "Country", "type": "String"}},
    {{"name": "Latitude", "type": "Double"}},
    {{"name": "Longitude", "type": "Double"}},
    {{"name": "Email", "type": "String"}},
    {{"name": "Phone", "type": "String"}},
    {{"name": "Fax", "type": "String"}},
    {{"name": "MobilePhone", "type": "String"}},
    {{"name": "Alias", "type": "String"}},
    {{"name": "CommunityNickname", "type": "String"}},
    {{"name": "IsActive", "type": "Boolean"}},
    {{"name": "TimeZoneSidKey", "type": "String"}},
    {{"name": "UserRoleId", "type": "String"}},
    {{"name": "LocaleSidKey", "type": "String"}},
    {{"name": "ReceivesInfoEmails", "type": "Boolean"}},
    {{"name": "ReceivesAdminInfoEmails", "type": "Boolean"}},
    {{"name": "EmailEncodingKey", "type": "String"}},
    {{"name": "ProfileId", "type": "String"}},
    {{"name": "UserType", "type": "String"}},
    {{"name": "LanguageLocaleKey", "type": "String"}},
    {{"name": "EmployeeNumber", "type": "String"}},
    {{"name": "DelegatedApproverId", "type": "String"}},
    {{"name": "ManagerId", "type": "String"}},
    {{"name": "LastLoginDate", "type": "Datetime"}},
    {{"name": "LastPasswordChangeDate", "type": "Datetime"}},
    {{"name": "OfflineTrialExpirationDate", "type": "Datetime"}},
    {{"name": "OfflinePdaTrialExpirationDate", "type": "Datetime"}},
    {{"name": "UserPermissionsMarketingUser", "type": "Boolean"}},
    {{"name": "UserPermissionsOfflineUser", "type": "Boolean"}},
    {{"name": "UserPermissionsCallCenterAutoLogin", "type": "Boolean"}},
    {{"name": "UserPermissionsMobileUser", "type": "Boolean"}},
    {{"name": "UserPermissionsSFContentUser", "type": "Boolean"}},
    {{"name": "UserPermissionsKnowledgeUser", "type": "Boolean"}},
    {{"name": "UserPermissionsInteractionUser", "type": "Boolean"}},
    {{"name": "UserPermissionsSupportUser", "type": "Boolean"}},
    {{"name": "UserPermissionsJigsawProspectingUser", "type": "Boolean"}},
    {{"name": "UserPermissionsSiteforceContributorUser", "type": "Boolean"}},
    {{"name": "UserPermissionsSiteforcePublisherUser", "type": "Boolean"}},
    {{"name": "UserPermissionsWorkDotComUserFeature", "type": "Boolean"}},
    {{"name": "ForecastEnabled", "type": "Boolean"}},
    {{"name": "UserPreferencesActivityRemindersPopup", "type": "Boolean"}},
    {{"name": "UserPreferencesEventRemindersCheckboxDefault", "type": "Boolean"}},
    {{"name": "UserPreferencesTaskRemindersCheckboxDefault", "type": "Boolean"}},
    {{"name": "UserPreferencesReminderSoundOff", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableAllFeedsEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableFollowersEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableProfilePostEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableChangeCommentEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableLaterCommentEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisProfPostCommentEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesContentNoEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesContentEmailAsAndWhen", "type": "Boolean"}},
    {{"name": "UserPreferencesApexPagesDeveloperMode", "type": "Boolean"}},
    {{"name": "UserPreferencesReceiveNoNotificationsAsApprover", "type": "Boolean"}},
    {{"name": "UserPreferencesReceiveNotificationsAsDelegatedApprover", "type": "Boolean"}},
    {{"name": "UserPreferencesHideCSNGetChatterMobileTask", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableMentionsPostEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisMentionsCommentEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesHideCSNDesktopTask", "type": "Boolean"}},
    {{"name": "UserPreferencesHideChatterOnboardingSplash", "type": "Boolean"}},
    {{"name": "UserPreferencesHideSecondChatterOnboardingSplash", "type": "Boolean"}},
    {{"name": "UserPreferencesDisCommentAfterLikeEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableLikeEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesSortFeedByComment", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableMessageEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableBookmarkEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableSharePostEmail", "type": "Boolean"}},
    {{"name": "UserPreferencesEnableAutoSubForFeeds", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableFileShareNotificationsForApi", "type": "Boolean"}},
    {{"name": "UserPreferencesShowTitleToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowManagerToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowEmailToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowWorkPhoneToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowMobilePhoneToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowFaxToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowStreetAddressToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowCityToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowStateToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowPostalCodeToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowCountryToExternalUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowProfilePicToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowTitleToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowCityToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowStateToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowPostalCodeToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowCountryToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesShowProfilePicToGuestUsers", "type": "Boolean"}},
    {{"name": "UserPreferencesDisableFeedbackEmail", "type": "Boolean"}}
  ]
}}
"""
sfdc_tables_list = ["salesforce_opportunities", "salesforce_accounts"] # Only using these two tables
# Original list commented out:
# sfdc_tables_list = ["salesforce_opportunities", "salesforce_tasks", "salesforce_accounts", "salesforce_contacts", "salesforce_leads", "salesforce_users", "salesforce_campaigns"]

SFDC_TABLE_SCHEMAS = {
    "salesforce_opportunities": OPPORTUNITY_TABLE_SCHEMA_PROMPT,
    "salesforce_accounts": ACCOUNT_TABLE_SCHEMA_PROMPT,
    # Commented out tables we're not using:
    # "salesforce_tasks": TASK_TABLE_SCHEMA_PROMPT,
    # "salesforce_contacts": CONTACT_TABLE_SCHEMA_PROMPT,
    # "salesforce_leads": LEAD_TABLE_SCHEMA_PROMPT,
    # "salesforce_users": USER_TABLE_SCHEMA_PROMPT,
    # "salesforce_campaigns": CAMPAIGN_TABLE_SCHEMA_PROMPT,
}





