"""
LLM-Powered Metadata Generator

This module uses LLMs to dynamically generate metadata for ML tool functions,
replacing hardcoded mappings with intelligent analysis.
"""

import json
import re
from typing import Dict, List, Any, Optional, Union, Tuple
from dataclasses import dataclass
from datetime import datetime
import inspect


from app.core.dependencies import get_llm
from langchain.schema import HumanMessage, SystemMessage
from langchain.prompts import PromptTemplate


@dataclass
class LLMGeneratedMetadata:
    """Metadata generated by LLM for a function."""
    category: str
    subcategory: str
    description: str
    use_cases: List[str]
    data_requirements: List[str]
    complexity_level: str
    tags: List[str]
    keywords: List[str]
    related_functions: List[str]
    confidence_score: float


class LLMMetadataGenerator:
    """LLM-powered metadata generator for ML functions."""
    
    def __init__(self, llm_model: str = "gpt-3.5-turbo", temperature: float = 0.1):
        """Initialize the LLM metadata generator.
        
        Args:
            llm_model: LLM model to use for metadata generation
            temperature: Temperature for LLM responses
        """
        self.llm = get_llm()
        self.function_cache = {}
        
        # Initialize prompts
        self._initialize_prompts()
    
    def _initialize_prompts(self):
        """Initialize LLM prompts for different tasks."""
        
        # Function analysis prompt
        self.function_analysis_prompt = PromptTemplate(
            input_variables=["function_name", "docstring", "source_code", "parameters"],
            template="""
Analyze the following ML function and generate comprehensive metadata:

Function Name: {function_name}
Docstring: {docstring}
Source Code: {source_code}
Parameters: {parameters}

Please provide a JSON response with the following structure:
{{
    "category": "Primary category (anomaly_detection, time_series, segmentation, cohort_analysis, metrics, operations, moving_averages, risk_analysis, funnel_analysis, trend_analysis, group_aggregation, or other)",
    "subcategory": "More specific subcategory within the main category",
    "description": "Clear, concise description of what this function does",
    "use_cases": ["List of specific use cases this function addresses"],
    "data_requirements": ["List of data requirements (e.g., 'Time series data', 'Grouped data', 'Numerical data')"],
    "complexity_level": "simple, intermediate, or advanced",
    "tags": ["Relevant tags for this function"],
    "keywords": ["Keywords that would help find this function"],
    "related_functions": ["Names of related functions that might be used together"],
    "confidence_score": 0.95
}}

Guidelines:
- Be specific and accurate in categorization
- Include practical use cases
- Consider the function's parameters and docstring
- Generate relevant keywords for search
- Assess complexity based on function logic and parameters
- Confidence score should reflect how certain you are about the analysis (0.0 to 1.0)
"""
        )
        
        # Query analysis prompt
        self.query_analysis_prompt = PromptTemplate(
            input_variables=["query", "available_functions"],
            template="""
Given a user query and a list of available ML functions, identify the most relevant functions.

User Query: {query}
Available Functions: {available_functions}

Please provide a JSON response with the following structure:
{{
    "relevant_functions": [
        {{
            "function_name": "function_name",
            "relevance_score": 0.95,
            "reasoning": "Why this function is relevant to the query"
        }}
    ],
    "query_intent": "What the user is trying to accomplish",
    "suggested_categories": ["Categories that might be relevant"],
    "data_requirements": ["What kind of data the user likely has"]
}}

Guidelines:
- Score relevance from 0.0 to 1.0
- Consider function names, descriptions, and use cases
- Provide clear reasoning for each selection
- Identify the user's intent
- Suggest relevant categories
"""
        )
        
        # Category classification prompt
        self.category_classification_prompt = PromptTemplate(
            input_variables=["function_name", "description", "use_cases"],
            template="""
Classify this function into the most appropriate category:

Function Name: {function_name}
Description: {description}
Use Cases: {use_cases}

Available Categories:
- anomaly_detection: Functions for detecting anomalies and outliers
- time_series: Functions for time series analysis and forecasting
- cohort_analysis: Functions for cohort and retention analysis
- segmentation: Functions for customer and data segmentation
- metrics: Functions for calculating various metrics and statistics
- operations: Functions for data operations and transformations
- moving_averages: Functions for moving averages and rolling calculations
- risk_analysis: Functions for risk analysis and financial metrics
- funnel_analysis: Functions for funnel and conversion analysis
- trend_analysis: Functions for trend analysis and forecasting
- group_aggregation: Functions for group-based aggregation operations

Please provide a JSON response:
{{
    "primary_category": "Most appropriate category",
    "secondary_categories": ["Other relevant categories"],
    "confidence": 0.95,
    "reasoning": "Why this category was chosen"
}}
"""
        )
    
    def generate_function_metadata(self, func: callable, module_name: str) -> LLMGeneratedMetadata:
        """Generate comprehensive metadata for a function using LLM.
        
        Args:
            func: The function to analyze
            module_name: Name of the module containing the function
            
        Returns:
            LLMGeneratedMetadata object
        """
        # Check cache first
        cache_key = f"{module_name}.{func.__name__}"
        if cache_key in self.function_cache:
            return self.function_cache[cache_key]
        
        # Extract function information
        function_name = func.__name__
        docstring = inspect.getdoc(func) or ""
        source_code = self._get_function_source(func)
        parameters = self._extract_parameters(func)
        
        # Prepare prompt
        prompt = self.function_analysis_prompt.format(
            function_name=function_name,
            docstring=docstring,
            source_code=source_code,
            parameters=json.dumps(parameters, indent=2)
        )
        
        try:
            # Get LLM response
            messages = [
                SystemMessage(content="You are an expert ML engineer analyzing function metadata. Provide accurate, detailed analysis in JSON format."),
                HumanMessage(content=prompt)
            ]
            
            response = self.llm(messages)
            metadata_dict = json.loads(response.content)
            
            # Create metadata object
            metadata = LLMGeneratedMetadata(
                category=metadata_dict.get("category", "other"),
                subcategory=metadata_dict.get("subcategory", ""),
                description=metadata_dict.get("description", ""),
                use_cases=metadata_dict.get("use_cases", []),
                data_requirements=metadata_dict.get("data_requirements", []),
                complexity_level=metadata_dict.get("complexity_level", "intermediate"),
                tags=metadata_dict.get("tags", []),
                keywords=metadata_dict.get("keywords", []),
                related_functions=metadata_dict.get("related_functions", []),
                confidence_score=metadata_dict.get("confidence_score", 0.8)
            )
            
            # Cache the result
            self.function_cache[cache_key] = metadata
            
            return metadata
            
        except Exception as e:
            print(f"Error generating metadata for {function_name}: {e}")
            # Return fallback metadata
            return self._generate_fallback_metadata(func, module_name)
    
    def find_relevant_functions(self, query: str, available_functions: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Find relevant functions for a query using LLM.
        
        Args:
            query: User query
            available_functions: List of available function metadata
            
        Returns:
            List of relevant functions with scores
        """
        # Prepare function list for prompt
        function_list = []
        for func in available_functions:
            function_list.append({
                "name": func.get("name", ""),
                "description": func.get("description", ""),
                "category": func.get("category", ""),
                "use_cases": func.get("use_cases", []),
                "tags": func.get("tags", [])
            })
        
        # Prepare prompt
        prompt = self.query_analysis_prompt.format(
            query=query,
            available_functions=json.dumps(function_list, indent=2)
        )
        
        try:
            # Get LLM response
            messages = [
                SystemMessage(content="You are an expert ML engineer helping users find the right functions. Provide accurate, relevant recommendations in JSON format."),
                HumanMessage(content=prompt)
            ]
            
            response = self.llm(messages)
            result = json.loads(response.content)
            
            return result.get("relevant_functions", [])
            
        except Exception as e:
            print(f"Error finding relevant functions: {e}")
            return []
    
    def classify_function_category(self, function_name: str, description: str, use_cases: List[str]) -> Dict[str, Any]:
        """Classify a function into appropriate categories using LLM.
        
        Args:
            function_name: Name of the function
            description: Function description
            use_cases: List of use cases
            
        Returns:
            Classification result
        """
        # Prepare prompt
        prompt = self.category_classification_prompt.format(
            function_name=function_name,
            description=description,
            use_cases=json.dumps(use_cases)
        )
        
        try:
            # Get LLM response
            messages = [
                SystemMessage(content="You are an expert ML engineer classifying functions. Provide accurate categorization in JSON format."),
                HumanMessage(content=prompt)
            ]
            
            response = self.llm(messages)
            return json.loads(response.content)
            
        except Exception as e:
            print(f"Error classifying function {function_name}: {e}")
            return {
                "primary_category": "other",
                "secondary_categories": [],
                "confidence": 0.5,
                "reasoning": "Error in classification"
            }
    
    def generate_use_case_mappings(self, functions: List[Dict[str, Any]]) -> Dict[str, List[str]]:
        """Generate use case to function mappings using LLM.
        
        Args:
            functions: List of function metadata
            
        Returns:
            Dictionary mapping use cases to relevant functions
        """
        use_case_mappings = {}
        
        for func in functions:
            use_cases = func.get("use_cases", [])
            function_name = func.get("name", "")
            
            for use_case in use_cases:
                if use_case not in use_case_mappings:
                    use_case_mappings[use_case] = []
                use_case_mappings[use_case].append(function_name)
        
        return use_case_mappings
    
    def generate_data_requirement_mappings(self, functions: List[Dict[str, Any]]) -> Dict[str, List[str]]:
        """Generate data requirement to function mappings using LLM.
        
        Args:
            functions: List of function metadata
            
        Returns:
            Dictionary mapping data requirements to relevant functions
        """
        data_mappings = {}
        
        for func in functions:
            data_requirements = func.get("data_requirements", [])
            function_name = func.get("name", "")
            
            for requirement in data_requirements:
                if requirement not in data_mappings:
                    data_mappings[requirement] = []
                data_mappings[requirement].append(function_name)
        
        return data_mappings
    
    def _get_function_source(self, func: callable) -> str:
        """Get source code of a function."""
        try:
            return inspect.getsource(func)
        except:
            return ""
    
    def _extract_parameters(self, func: callable) -> Dict[str, Any]:
        """Extract parameter information from a function."""
        parameters = {}
        sig = inspect.signature(func)
        
        for param_name, param in sig.parameters.items():
            parameters[param_name] = {
                "name": param_name,
                "type": str(param.annotation) if param.annotation != inspect.Parameter.empty else "Any",
                "default": param.default if param.default != inspect.Parameter.empty else None,
                "required": param.default == inspect.Parameter.empty
            }
        
        return parameters
    
    def _generate_fallback_metadata(self, func: callable, module_name: str) -> LLMGeneratedMetadata:
        """Generate fallback metadata when LLM fails."""
        function_name = func.__name__
        
        # Simple heuristic-based classification
        category = "other"
        if "anomaly" in function_name.lower() or "outlier" in function_name.lower():
            category = "anomaly_detection"
        elif "forecast" in function_name.lower() or "trend" in function_name.lower():
            category = "time_series"
        elif "segment" in function_name.lower() or "cluster" in function_name.lower():
            category = "segmentation"
        elif "cohort" in function_name.lower() or "retention" in function_name.lower():
            category = "cohort_analysis"
        elif "moving" in function_name.lower() or "rolling" in function_name.lower():
            category = "moving_averages"
        elif "risk" in function_name.lower() or "var" in function_name.lower():
            category = "risk_analysis"
        elif "funnel" in function_name.lower() or "conversion" in function_name.lower():
            category = "funnel_analysis"
        elif "metric" in function_name.lower() or "stat" in function_name.lower():
            category = "metrics"
        
        return LLMGeneratedMetadata(
            category=category,
            subcategory="",
            description=f"Function {function_name} from {module_name}",
            use_cases=[],
            data_requirements=[],
            complexity_level="intermediate",
            tags=[],
            keywords=[],
            related_functions=[],
            confidence_score=0.5
        )
    
    def clear_cache(self):
        """Clear the function metadata cache."""
        self.function_cache.clear()
    
    def get_cache_stats(self) -> Dict[str, Any]:
        """Get cache statistics."""
        return {
            "cached_functions": len(self.function_cache),
            "cache_keys": list(self.function_cache.keys())
        }


class DynamicFunctionMatcher:
    """Dynamic function matcher using LLM for semantic matching."""
    
    def __init__(self, metadata_generator: LLMMetadataGenerator):
        """Initialize the dynamic function matcher.
        
        Args:
            metadata_generator: LLM metadata generator instance
        """
        self.metadata_generator = metadata_generator
        self.function_registry = {}
    
    def register_functions(self, functions: List[Dict[str, Any]]):
        """Register functions for matching.
        
        Args:
            functions: List of function metadata dictionaries
        """
        for func in functions:
            self.function_registry[func["name"]] = func
    
    def find_best_matches(self, query: str, max_results: int = 5) -> List[Dict[str, Any]]:
        """Find the best matching functions for a query.
        
        Args:
            query: User query
            max_results: Maximum number of results to return
            
        Returns:
            List of matching functions with scores
        """
        if not self.function_registry:
            return []
        
        # Convert registry to list for LLM analysis
        available_functions = list(self.function_registry.values())
        
        # Get LLM recommendations
        relevant_functions = self.metadata_generator.find_relevant_functions(
            query, available_functions
        )
        
        # Sort by relevance score and limit results
        relevant_functions.sort(key=lambda x: x.get("relevance_score", 0), reverse=True)
        
        return relevant_functions[:max_results]
    
    def find_functions_by_use_case(self, use_case: str, max_results: int = 5) -> List[Dict[str, Any]]:
        """Find functions suitable for a specific use case.
        
        Args:
            use_case: Use case description
            max_results: Maximum number of results to return
            
        Returns:
            List of suitable functions
        """
        # Use LLM to find relevant functions
        return self.find_best_matches(f"Use case: {use_case}", max_results)
    
    def find_functions_by_data_requirements(self, data_columns: List[str], max_results: int = 5) -> List[Dict[str, Any]]:
        """Find functions suitable for specific data columns.
        
        Args:
            data_columns: List of available data columns
            max_results: Maximum number of results to return
            
        Returns:
            List of suitable functions
        """
        # Create query based on data columns
        query = f"Functions that work with data columns: {', '.join(data_columns)}"
        
        return self.find_best_matches(query, max_results)
    
    def get_function_recommendations(self, function_name: str, max_results: int = 5) -> List[Dict[str, Any]]:
        """Get function recommendations based on a given function.
        
        Args:
            function_name: Name of the function to get recommendations for
            max_results: Maximum number of recommendations
            
        Returns:
            List of recommended functions
        """
        if function_name not in self.function_registry:
            return []
        
        function_info = self.function_registry[function_name]
        
        # Create query based on function characteristics
        query_parts = [
            function_info.get("description", ""),
            f"category: {function_info.get('category', '')}",
            f"use cases: {', '.join(function_info.get('use_cases', []))}"
        ]
        
        query = " ".join(filter(None, query_parts))
        
        # Find similar functions
        recommendations = self.find_best_matches(query, max_results + 1)
        
        # Filter out the original function
        recommendations = [rec for rec in recommendations if rec.get("function_name") != function_name]
        
        return recommendations[:max_results]


def create_llm_metadata_generator(llm_model: str = "gpt-3.5-turbo") -> LLMMetadataGenerator:
    """Create an LLM metadata generator instance.
    
    Args:
        llm_model: LLM model to use
        
    Returns:
        LLMMetadataGenerator instance
    """
    return LLMMetadataGenerator(llm_model=llm_model)


def create_dynamic_function_matcher(metadata_generator: LLMMetadataGenerator) -> DynamicFunctionMatcher:
    """Create a dynamic function matcher instance.
    
    Args:
        metadata_generator: LLM metadata generator instance
        
    Returns:
        DynamicFunctionMatcher instance
    """
    return DynamicFunctionMatcher(metadata_generator)
