"""
Planned CSOD executors (v5) — node_fn None until LangGraph nodes exist.
Merged into EXECUTOR_REGISTRY for planner context.
"""
from typing import Any, Dict


def _n(start: str, end: str, detail: str) -> Dict[str, str]:
    return {"start": start, "end": end, "detail": detail}


def planned_executors_v5() -> Dict[str, Dict[str, Any]]:
    """Executors from csod_refactor_design §2a without implemented node_fn yet."""
    return {
        "anomaly_detector": {
            "executor_id": "anomaly_detector",
            "type": "sql",
            "display_name": "Anomaly Detector",
            "description": "Flags statistical anomalies; uses csod_causal_edges for upstream/downstream traversal (no spine Shapley).",
            "capabilities": ["anomaly_detection"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["csod_causal_edges"],
            "output_fields": [
                "csod_anomaly_report",
                "csod_flagged_records",
                "csod_deviation_summary",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": True,
            "narrative": _n(
                "I'm scanning your training data for unusual patterns and statistical outliers.",
                "I've identified {anomaly_count} anomalies. Checking whether each originates upstream.",
                "Checking {metric_name} — {threshold}σ threshold, {window}-day window.",
            ),
            "node_fn": None,
            "prompt_file": None,
            "implemented": False,
        },
        "funnel_analyzer": {
            "executor_id": "funnel_analyzer",
            "type": "sql",
            "display_name": "Funnel Analyzer",
            "description": "Stage conversion/dropout; optional csod_causal_edges for transition weights.",
            "capabilities": ["funnel_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["csod_causal_edges", "scoping_filters.funnel_stages"],
            "output_fields": [
                "csod_funnel_chart",
                "csod_stage_conversion_rates",
                "csod_dropout_analysis",
            ],
            "dt_required": True,
            "cce_mode": "optional",
            "can_be_direct": True,
            "narrative": _n(
                "I'm mapping your learner journey through each training stage.",
                "Funnel built across {stage_count} stages. Largest drop-off: {dropout_stage}.",
                "Calculating conversion from {from_stage} to {to_stage}.",
            ),
            "node_fn": None,
            "prompt_file": None,
            "implemented": False,
        },
        "risk_predictor": {
            "executor_id": "risk_predictor",
            "type": "sql",
            "display_name": "Risk Predictor",
            "description": "Compliance risk scoring; Shapley vs compliance_posture computed internally into csod_risk_scores[].shapley_contribution.",
            "capabilities": ["predictive_risk_analysis"],
            "required_inputs": [
                "dt_scored_metrics",
                "csod_resolved_schemas",
                "csod_causal_edges",
            ],
            "optional_inputs": ["scoping_filters.risk_threshold"],
            "output_fields": [
                "csod_risk_scores",
                "csod_at_risk_learner_list",
                "csod_intervention_plan",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": True,
            "narrative": _n(
                "I'm scoring each learner for compliance risk — weighing deadlines, progress, and engagement patterns.",
                "{at_risk_count} learners flagged as high-risk before the deadline.",
                "Computing risk score for {cohort_name} using causal feature weights.",
            ),
            "node_fn": None,
            "prompt_file": None,
            "implemented": False,
        },
        "behavioral_analyzer": {
            "executor_id": "behavioral_analyzer",
            "type": "sql",
            "display_name": "Behavioral Analyzer",
            "description": "Engagement segmentation; optional edge paths to outcomes.",
            "capabilities": ["behavioral_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["csod_causal_edges"],
            "output_fields": [
                "csod_behavioral_patterns",
                "csod_engagement_scores",
                "csod_behavioral_segments",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": True,
            "narrative": _n(
                "I'm analysing how learners engage — login patterns, session depth, content choices.",
                "Segmented {learner_count} learners into {segment_count} engagement profiles.",
                "Computing {feature} for learner cohort.",
            ),
            "node_fn": None,
            "prompt_file": None,
            "implemented": False,
        },
        "crown_jewel_ranker": {
            "executor_id": "crown_jewel_ranker",
            "type": "ml",
            "display_name": "Crown Jewel Ranker",
            "description": "Ranks by DT composite + csod_causal_centrality (topology, not Shapley).",
            "capabilities": ["crown_jewel_analysis"],
            "required_inputs": ["dt_scored_metrics"],
            "optional_inputs": ["csod_causal_centrality"],
            "output_fields": [
                "csod_ranked_metrics",
                "csod_impact_scores",
                "csod_priority_recommendations",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": True,
            "narrative": _n(
                "I'm ranking your metrics by business impact — combining relevance scores with causal influence.",
                "Top {top_n} crown jewel metrics identified. {retire_count} candidates for retirement.",
                "Scoring {metric_name}: DT={dt_score}, centrality={centrality_score}.",
            ),
            "node_fn": None,
            "prompt_file": "16_crown_jewel_analysis.md",
            "implemented": False,
        },
        "gap_analyzer": {
            "executor_id": "gap_analyzer",
            "type": "ml",
            "display_name": "Gap Analyzer",
            "description": "Gap vs target; internal Shapley in csod_gap_report.root_cause_shapley using csod_causal_edges.",
            "capabilities": ["gap_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["csod_causal_edges", "scoping_filters.target_source"],
            "output_fields": [
                "csod_gap_report",
                "csod_metric_deltas",
                "csod_priority_gaps",
                "csod_remediation_recommendations",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": True,
            "narrative": _n(
                "I'm measuring the gap between where you are and where you need to be.",
                "{gap_count} gaps found. Largest: {top_gap_name} at {top_gap_pct}% below target.",
                "Decomposing root cause for {metric_name} — tracing contribution of upstream factors.",
            ),
            "node_fn": None,
            "prompt_file": "17_gap_analysis.md",
            "implemented": False,
        },
        "cohort_comparator": {
            "executor_id": "cohort_comparator",
            "type": "ml",
            "display_name": "Cohort Comparator",
            "description": "Cohort comparison; optional edges for structural dependency tests.",
            "capabilities": ["cohort_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["scoping_filters.cohort_definition", "csod_causal_edges"],
            "output_fields": [
                "csod_cohort_comparison",
                "csod_group_metrics",
                "csod_segmentation_insights",
            ],
            "dt_required": True,
            "cce_mode": "optional",
            "can_be_direct": True,
            "narrative": _n(
                "I'm splitting your learners into groups and comparing performance across them.",
                "Compared {cohort_count} cohorts. {top_cohort} leads on {top_metric}.",
                "Computing {metric_name} for {cohort_name}.",
            ),
            "node_fn": None,
            "prompt_file": "18_cohort_analysis.md",
            "implemented": False,
        },
        "benchmark_comparator": {
            "executor_id": "benchmark_comparator",
            "type": "ml",
            "display_name": "Benchmark Comparator",
            "description": "Benchmark comparison; no causal graph required.",
            "capabilities": ["benchmark_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": ["scoping_filters.benchmark_source"],
            "output_fields": [
                "csod_benchmark_report",
                "csod_performance_vs_baseline",
                "csod_ranking",
            ],
            "dt_required": True,
            "cce_mode": "disabled",
            "can_be_direct": True,
            "narrative": _n(
                "I'm comparing your metrics against the selected benchmark.",
                "{above_count} metrics above benchmark, {below_count} below.",
                "Comparing {metric_name} against {benchmark_source}.",
            ),
            "node_fn": None,
            "prompt_file": "19_benchmark_analysis.md",
            "implemented": False,
        },
        "skill_gap_assessor": {
            "executor_id": "skill_gap_assessor",
            "type": "ml",
            "display_name": "Skill Gap Assessor",
            "description": "Competency vs completion; optional csod_causal_edges for training priority ordering.",
            "capabilities": ["skill_gap_analysis"],
            "required_inputs": ["dt_scored_metrics", "csod_resolved_schemas"],
            "optional_inputs": [
                "csod_causal_edges",
                "scoping_filters.skill_domain",
                "scoping_filters.job_role",
            ],
            "output_fields": [
                "csod_skill_gap_matrix",
                "csod_competency_heatmap",
                "csod_training_priority_list",
            ],
            "dt_required": True,
            "cce_mode": "optional",
            "can_be_direct": True,
            "narrative": _n(
                "I'm measuring the gap between required competencies and current skill levels.",
                "{gap_skill_count} skill gaps identified. Top priority: {top_skill}.",
                "Assessing {skill_name} across {role_count} roles.",
            ),
            "node_fn": None,
            "prompt_file": "20_skill_gap_analysis.md",
            "implemented": False,
        },
        "roi_calculator": {
            "executor_id": "roi_calculator",
            "type": "ml",
            "display_name": "ROI Calculator",
            "description": "ROI with internal Shapley in program_roi_breakdown[].shapley_roi_share_pct.",
            "capabilities": ["training_roi_analysis"],
            "required_inputs": [
                "dt_scored_metrics",
                "csod_resolved_schemas",
                "csod_causal_edges",
            ],
            "optional_inputs": ["scoping_filters.cost_category"],
            "output_fields": [
                "csod_roi_report",
                "csod_cost_efficiency_analysis",
                "csod_impact_attribution",
            ],
            "dt_required": True,
            "cce_mode": "required",
            "can_be_direct": False,
            "narrative": _n(
                "I'm calculating the return on your training investment — tracing spend to compliance outcomes.",
                "Overall ROI: {roi_ratio}x. Highest-return program: {top_program}.",
                "Attributing impact to {program_type} training using causal structure.",
            ),
            "node_fn": None,
            "prompt_file": "21_roi_analysis.md",
            "implemented": False,
        },
        "dashboard_layout_resolver": {
            "executor_id": "dashboard_layout_resolver",
            "type": "layout",
            "display_name": "Dashboard Layout Resolver",
            "description": "Maps metric groups to sections/widgets; centrality orders leading first.",
            "capabilities": [
                "dashboard_generation_for_persona",
                "metrics_dashboard_plan",
            ],
            "required_inputs": ["dt_metric_groups", "csod_persona"],
            "optional_inputs": ["csod_causal_centrality"],
            "output_fields": ["csod_dt_layout"],
            "dt_required": True,
            "cce_mode": "optional",
            "can_be_direct": False,
            "narrative": _n(
                "I'm deciding how to arrange your metrics into a dashboard — which go on top, which become charts.",
                "Layout resolved: {section_count} sections, {widget_count} widgets.",
                "Assigning {metric_name} to {section} as {widget_type}.",
            ),
            "node_fn": None,
            "prompt_file": "26_dashboard_layout.md",
            "implemented": False,
        },
        "metrics_layout_resolver": {
            "executor_id": "metrics_layout_resolver",
            "type": "layout",
            "display_name": "Metrics Layout Resolver",
            "description": "Orders metric groups with leading/lagging from centrality.",
            "capabilities": [
                "metrics_dashboard_plan",
                "metrics_recommender_with_gold_plan",
                "crown_jewel_analysis",
                "metric_kpi_advisor",
            ],
            "required_inputs": ["dt_metric_groups", "dt_metric_decisions"],
            "optional_inputs": ["csod_causal_centrality"],
            "output_fields": ["csod_metrics_layout"],
            "dt_required": True,
            "cce_mode": "optional",
            "can_be_direct": False,
            "narrative": _n(
                "I'm ordering your metrics — leading indicators first, then the outcomes they drive.",
                "Metrics ordered into {group_count} goal-aligned groups.",
                "Tagging {metric_name} as {indicator_type} indicator.",
            ),
            "node_fn": None,
            "prompt_file": "27_metrics_layout.md",
            "implemented": False,
        },
    }
