# Generated Pipeline Code
# Generated by SelfCorrectingPipelineCodeGenerator
# Date: 2025-08-29 09:26:56
# Question: What are the daily trends of transaction amounts by region and project?
#============================================================

import pandas as pd
import numpy as np
from datetime import datetime
import os
from pathlib import Path
from app.tools.mltools.metrics_tools import MetricsPipe, GroupBy
from app.tools.mltools.trendanalysistools import TrendPipe, aggregate_by_time, calculate_growth_rates, calculate_moving_average
from app.tools.mltools.movingaverages import MovingAggrPipe, moving_apply_by_group
from app.tools.mltools.timeseriesanalysis import TimeSeriesPipe, variance_analysis



import pandas as pd
from sqlalchemy import create_engine

# --- Step 1: Configure your PostgreSQL connection ---
# It's recommended to use environment variables or secure vaults for sensitive information like passwords.
# Replace the placeholder values with your actual PostgreSQL connection information.
"""
POSTGRES_HOST = "unedadevpostgresql.postgres.database.azure.com"
POSTGRES_PORT = 5432
POSTGRES_DBNAME = "phenom_genai_dataservices"
POSTGRES_USER = "pixentia"
POSTGRES_PASSWORD = "FLc%26dL%40M9A5Q7wI%3B"  # Use secure methods in production
POSTGRES_SSL_MODE = "require"

# --- Step 2: Create a SQLAlchemy engine for PostgreSQL ---
# The URL format for PostgreSQL using psycopg2 is:
# postgresql+psycopg2://user:password@host:port/database
try:
    connection_string = (
        f"postgresql+psycopg2://{POSTGRES_USER}:{POSTGRES_PASSWORD}@"
        f"{POSTGRES_HOST}:{POSTGRES_PORT}/{POSTGRES_DBNAME}"
        f"?sslmode={POSTGRES_SSL_MODE}"
    )
    
    # Create engine with connection pooling
    engine = create_engine(
        connection_string,
        pool_size=10,
        max_overflow=10,
        pool_timeout=30,
        pool_recycle=3600
    )
    
    print("✅ Successfully created PostgreSQL connection engine.")
    
    # Test the connection
    with engine.connect() as conn:
        result = conn.execute("SELECT version()")
        version = result.fetchone()[0]
        print(f"📊 Connected to: {version}")

except Exception as e:
    print(f"❌ Error creating PostgreSQL connection engine: {e}")
    raise
"""

# --- Step 3: Define your SQL query and read into a pandas DataFrame ---
query = """
    SELECT 
        DATE_TRUNC('day', transaction_date) as date,
        region,
        project,
        source_system,
        AVG(transaction_amount) as avg_amount,
        COUNT(*) as transaction_count,
        SUM(transaction_amount) as total_amount
    FROM financial_transactions 
    WHERE transaction_date >= CURRENT_DATE - INTERVAL '30 days'
    GROUP BY DATE_TRUNC('day', transaction_date), region, project, source_system
    ORDER BY date DESC, total_amount DESC
    """

def fetch_data_from_postgres(query, engine):
    """
    Fetch data from PostgreSQL and return a pandas DataFrame
    
    Args:
        query (str): SQL query to execute
        engine: SQLAlchemy engine object
        
    Returns:
        pandas.DataFrame: Retrieved data
        
    Raises:
        Exception: If there's an error executing the query or creating DataFrame
    """
    try:
        # Use pandas.read_sql_query() to execute the query and return a DataFrame.
        # The `engine` object handles the connection to PostgreSQL.
        pandas_df = pd.read_sql_query(query, engine)
        
        print()
        print("✅ Successfully fetched data and created a pandas DataFrame.")
        print(f"📊 Retrieved {len(pandas_df)} rows and {len(pandas_df.columns)} columns")
        print()
        print("📋 First 5 rows of the DataFrame:")
        print(pandas_df.head())
        
        print()
        print("📊 DataFrame info:")
        print(pandas_df.info())
        
        print()
        print("📊 DataFrame statistics:")
        print(pandas_df.describe())
        
        return pandas_df

    except Exception as e:
        print(f"❌ Error executing query or creating DataFrame: {e}")
        raise

def close_connection(engine):
    """
    Close the database connection pool
    
    Args:
        engine: SQLAlchemy engine object to close
    """
    if engine:
        engine.dispose()
        print("🔒 Connection pool closed.")




def run_pipeline(financial_data):
    
    # Step 1: Data Selection
    # Step 1: Data Selection
    """
    # Step 2: Aggregate Daily Transaction Amounts
    pipe = (
        TrendPipe.from_dataframe(financial_data)
        | aggregate_by_time(date_column='Date', metric_columns=['Transactional value'], time_period='D', aggregation='sum')
    )
    print("result of step 2")
    print(pipe.to_df().head(3).to_string())
    
    # Step 3: Calculate Growth Rates
    pipe = pipe | calculate_growth_rates(window=None, annualize=False, method='percentage')
    print("result of step 3")
    print(pipe.to_df().head(3).to_string())
    
    # Step 4: Calculate Moving Averages
    pipe = pipe | calculate_moving_average(window=7, method='simple')
    print("result of step 4")
    print(pipe.to_df().head(3).to_string())
    """
    # Aggregate Transaction Amounts by Date, Region, and Project
    result = (
        MetricsPipe.from_dataframe(financial_data)
        | GroupBy(by=['Date', 'Region', 'Project'], agg_dict={'Transactional value': 'sum'}, output_name='aggregated_transaction_amounts')
        ).to_df()
    print("result of step 1 after group by")
    print(result.head(3).to_string())
    result = result.reset_index()
    # Aggregate Daily Transaction Amounts
    # Visualize Daily Trends in Transaction Amounts
    result = (
        TrendPipe.from_dataframe(result)
        | aggregate_by_time(date_column='Date', metric_columns=['Transactional value'], time_period='D', aggregation='sum', fill_missing=True, include_current_period=False, time_name='time')
        ).to_df()
    print("result of step 2 after aggregate by time and plot forecast")
    print(result.head(3).to_string())
        # Step 2: Aggregate Daily Transaction Amounts
    result = (
        TrendPipe.from_dataframe(financial_data)
        | aggregate_by_time(date_column='Date', metric_columns=['Transactional value'], time_period='D', aggregation='sum')
        | calculate_growth_rates(window=None, annualize=False, method='percentage')
        | calculate_moving_average(window=7, method='simple')
        ).to_df(include_original=True)

    result = result.reset_index()


    # Calculate Daily Flux
    result = (
        MetricsPipe.from_dataframe(financial_data)
        | GroupBy(by=['Date', 'Project', 'Cost center', 'Department'], agg_dict={'Transactional value': 'sum'}, output_name='daily_flux')
        ).to_df()

    result = (
        MovingAggrPipe.from_dataframe(result)
        | moving_apply_by_group(columns='daily_flux', group_column='Project', function=(MetricsPipe.from_dataframe(...) | () | to_df()), window=5, min_periods=1, center=False, time_column='Date', output_suffix='_rolling_variance')
        ).to_df()

    # Visualize 5-Day Rolling Variance
    result = (
        TimeSeriesPipe.from_dataframe(result)
        | variance_analysis(columns='5-Day Rolling Variance', method='rolling', window=5, time_column='Date', group_columns=['Project'], suffix='_rolling_variance')
        ).to_df()
    print("result of step 2")
    print(result.head(3).to_string())
    # Return the final result as DataFrame
    return result

# Pipeline Execution Function
# ===========================



def execute_pipeline():
    """Execute the complete pipeline: Data Loading → ML Pipeline"""
    print('🚀 Starting Financial Data Pipeline')
    print('=' * 50)
    
    try:
        # Step 1: Load data using the generated data loader
        print('🔍 Step 1: Loading data...')
        print('💡 Note: Import and run your data loader first')
        print('   Example: from postgres_data_loader import *')
        print('   Then run the data loading code')
         # Load real financial transaction data from the CSV file for analysis
        # This replaces the sample data with actual BV Finance Flux data containing real transactions
        csv_file_path = "/Users/sameerm/ComplianceSpark/byziplatform/unstructured/genieml/data/inputs/bv_finance_flux_final.csv"
        # Use the functions
        try:
            financial_data = pd.read_csv(csv_file_path) #fetch_data_from_postgres(query, engine)
        except Exception as e:
            print(f"❌ Error in data fetching: {e}")
            raise
        finally:
            print("Connection closed")
            #close_connection(engine)
    
            # Load the CSV data
        #financial_data = pd.read_csv(csv_file_path)
        
        # Debug: Verify the DataFrame shape
        print(f"   📊 CSV DataFrame loaded: {financial_data.shape[0]} rows, {financial_data.shape[1]} columns")
        print(f"   📋 CSV columns: {list(financial_data.columns)}")
        
        # Display first few rows for verification
        print(f"   📋 First few rows:")
        print(financial_data.head(3).to_string())
        # Step 2: Execute the ML pipeline code
        print('🤖 Step 2: Executing ML pipeline...')

        result = run_pipeline(financial_data)
        print(result)
        # The generated ML code will use the DataFrame
        # Make sure you have a DataFrame named 'financial_data' available
        
        print('✅ ML pipeline executed successfully!')
        
    except Exception as e:
        print(f'❌ Pipeline failed: {e}')
        import traceback
        traceback.print_exc()
        raise e

# Example execution:
if __name__ == '__main__':
    print('🚀 Starting Financial Data Pipeline')
    print('=' * 50)
    
    try:
        # Execute the complete pipeline
        execute_pipeline()
        
        print(f'\n🎉 Pipeline completed successfully!')
        
    except Exception as e:
        print(f'\n❌ Pipeline failed: {e}')
        
    print('\n💡 Template Usage:')
    print('1. First run your data loader: python postgres_data_loader.py')
    print('2. Then run this pipeline: python generated_pipeline_code.py')
    print('3. Modify the data loader configuration as needed')
    print('4. Update the ML pipeline logic in the generated code section')
