import logging
import asyncio
from typing import Dict, List, Any, Optional, Union
from dataclasses import dataclass
from datetime import datetime

# Import document models and services
from app.services.docs.docmodels import Document, DocumentInsight
from app.services.docs.document_persistence_service import DocumentPersistenceService
from app.storage.documents import DocumentChromaStore

# Import the enhanced planner
from .enhanced_document_planner import (
    DocumentPlan, DocumentPlanStep, DocumentPlanningStrategy, 
    DocumentRetrievalResult, RetrievalGrade, EnhancedDocumentPlanner
)

logger = logging.getLogger("DocumentPlanExecutor")

@dataclass
class ExecutionResult:
    """Result of executing a document plan step"""
    step_number: int
    action: str
    success: bool
    result: Any
    error_message: Optional[str] = None
    execution_time: float = 0.0
    documents_processed: List[str] = None

@dataclass
class DocumentAnalysisResult:
    """Result of document analysis"""
    document_id: str
    analysis_type: str
    content: str
    metadata: Dict[str, Any]
    confidence: float
    key_insights: List[str]
    structured_data: Optional[Dict[str, Any]] = None

class DocumentPlanExecutor:
    """Executes document analysis plans generated by the EnhancedDocumentPlanner"""
    
    def __init__(self,
                 document_service: DocumentPersistenceService = None,
                 chroma_store: DocumentChromaStore = None,
                 llm=None):
        self.document_service = document_service
        self.chroma_store = chroma_store
        self.llm = llm
        
        # Initialize function registry for plan execution
        self.function_registry = self._build_function_registry()
    
    def _build_function_registry(self) -> Dict[str, callable]:
        """Build registry of available document analysis functions"""
        return {
            "analyze_document_content": self._analyze_document_content,
            "extract_relevant_information": self._extract_relevant_information,
            "synthesize_answer": self._synthesize_answer,
            "identify_most_relevant_documents": self._identify_most_relevant_documents,
            "extract_specific_information": self._extract_specific_information,
            "generate_focused_answer": self._generate_focused_answer,
            "analyze_document_metadata": self._analyze_document_metadata,
            "extract_comparative_data": self._extract_comparative_data,
            "perform_comparison": self._perform_comparison,
            "synthesize_comparative_answer": self._synthesize_comparative_answer,
            "identify_structured_content": self._identify_structured_content,
            "extract_structured_data": self._extract_structured_data,
            "format_structured_answer": self._format_structured_answer,
            "summarize_document_content": self._summarize_document_content,
            "generate_answer": self._generate_answer,
            "analyze_documents": self._analyze_documents
        }
    
    async def execute_plan(self, plan: DocumentPlan) -> Dict[str, Any]:
        """
        Execute a document analysis plan
        
        Args:
            plan: The document plan to execute
            
        Returns:
            Dictionary containing execution results and final answer
        """
        logger.info(f"Executing document plan with strategy: {plan.strategy}")
        
        execution_results = {
            "original_question": plan.original_question,
            "reframed_question": plan.reframed_question,
            "strategy": plan.strategy,
            "confidence": plan.confidence,
            "retrieval_grade": plan.retrieval_result.retrieval_grade,
            "documents_available": len(plan.retrieval_result.documents),
            "execution_results": [],
            "final_answer": None,
            "execution_successful": True,
            "total_execution_time": 0.0
        }
        
        start_time = datetime.now()
        
        try:
            # Execute each step in the plan
            step_results = []
            for step in plan.steps:
                step_result = await self._execute_step(step, plan.retrieval_result)
                step_results.append(step_result)
                execution_results["execution_results"].append(step_result)
                
                if not step_result.success:
                    logger.error(f"Step {step.step_number} failed: {step_result.error_message}")
                    execution_results["execution_successful"] = False
                    break
            
            # Generate final answer if all steps succeeded
            if execution_results["execution_successful"]:
                execution_results["final_answer"] = await self._generate_final_answer(
                    plan, step_results
                )
            
        except Exception as e:
            logger.error(f"Error executing plan: {e}")
            execution_results["execution_successful"] = False
            execution_results["error"] = str(e)
        
        finally:
            execution_results["total_execution_time"] = (
                datetime.now() - start_time
            ).total_seconds()
        
        return execution_results
    
    async def _execute_step(self, 
                          step: DocumentPlanStep,
                          retrieval_result: DocumentRetrievalResult) -> ExecutionResult:
        """Execute a single step in the plan"""
        
        start_time = datetime.now()
        
        try:
            # Get the function for this step
            if step.action not in self.function_registry:
                return ExecutionResult(
                    step_number=step.step_number,
                    action=step.action,
                    success=False,
                    result=None,
                    error_message=f"Function '{step.action}' not found in registry",
                    execution_time=0.0,
                    documents_processed=[]
                )
            
            function = self.function_registry[step.action]
            
            # Execute the function
            result = await function(step, retrieval_result)
            
            execution_time = (datetime.now() - start_time).total_seconds()
            
            return ExecutionResult(
                step_number=step.step_number,
                action=step.action,
                success=True,
                result=result,
                execution_time=execution_time,
                documents_processed=step.target_documents
            )
            
        except Exception as e:
            execution_time = (datetime.now() - start_time).total_seconds()
            logger.error(f"Error executing step {step.step_number}: {e}")
            
            return ExecutionResult(
                step_number=step.step_number,
                action=step.action,
                success=False,
                result=None,
                error_message=str(e),
                execution_time=execution_time,
                documents_processed=step.target_documents
            )
    
    # Document analysis functions
    
    async def _analyze_document_content(self, 
                                      step: DocumentPlanStep,
                                      retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Analyze document content comprehensively"""
        
        target_docs = self._get_target_documents(step, retrieval_result)
        analysis_results = []
        
        for doc in target_docs:
            analysis = DocumentAnalysisResult(
                document_id=str(doc.document_id),
                analysis_type="content_analysis",
                content=doc.content[:2000],  # Limit content length
                metadata={
                    "document_type": doc.document_type,
                    "source_type": doc.source_type,
                    "created_at": doc.created_at.isoformat() if doc.created_at else None
                },
                confidence=0.8,
                key_insights=self._extract_key_insights(doc.content)
            )
            analysis_results.append(analysis)
        
        return {
            "analysis_type": "comprehensive_content_analysis",
            "documents_analyzed": len(target_docs),
            "results": [self._serialize_analysis_result(ar) for ar in analysis_results]
        }
    
    async def _extract_relevant_information(self, 
                                          step: DocumentPlanStep,
                                          retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Extract information relevant to the query"""
        
        query = step.parameters.get("query", "")
        relevance_threshold = step.parameters.get("relevance_threshold", 0.7)
        target_docs = self._get_target_documents(step, retrieval_result)
        
        relevant_info = []
        
        for doc in target_docs:
            # Simple relevance scoring based on keyword matching
            relevance_score = self._calculate_relevance_score(query, doc.content)
            
            if relevance_score >= relevance_threshold:
                relevant_info.append({
                    "document_id": str(doc.document_id),
                    "relevance_score": relevance_score,
                    "content_snippet": self._extract_relevant_snippet(query, doc.content),
                    "metadata": {
                        "document_type": doc.document_type,
                        "source_type": doc.source_type
                    }
                })
        
        return {
            "query": query,
            "relevance_threshold": relevance_threshold,
            "relevant_documents": relevant_info,
            "total_found": len(relevant_info)
        }
    
    async def _synthesize_answer(self, 
                               step: DocumentPlanStep,
                               retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Synthesize a comprehensive answer from all sources"""
        
        format_type = step.parameters.get("format", "comprehensive")
        include_sources = step.parameters.get("include_sources", True)
        
        # Collect all relevant information
        target_docs = self._get_target_documents(step, retrieval_result)
        
        synthesis_data = {
            "format": format_type,
            "include_sources": include_sources,
            "source_documents": [
                {
                    "id": str(doc.document_id),
                    "type": doc.document_type,
                    "source": doc.source_type,
                    "content_preview": doc.content[:500]
                }
                for doc in target_docs
            ],
            "key_insights": [],
            "synthesized_answer": "Synthesized answer based on document analysis"
        }
        
        # Extract key insights from all documents
        for doc in target_docs:
            insights = self._extract_key_insights(doc.content)
            synthesis_data["key_insights"].extend(insights)
        
        return synthesis_data
    
    async def _identify_most_relevant_documents(self, 
                                              step: DocumentPlanStep,
                                              retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Identify the most relevant documents from the retrieval result"""
        
        max_docs = step.parameters.get("max_docs", 3)
        relevance_threshold = step.parameters.get("relevance_threshold", 0.5)
        
        # Use the relevance scores from retrieval result
        doc_scores = list(zip(retrieval_result.documents, retrieval_result.relevance_scores))
        
        # Sort by relevance score
        doc_scores.sort(key=lambda x: x[1], reverse=True)
        
        # Filter by threshold and limit
        relevant_docs = [
            doc for doc, score in doc_scores 
            if score >= relevance_threshold
        ][:max_docs]
        
        return {
            "max_documents": max_docs,
            "relevance_threshold": relevance_threshold,
            "selected_documents": [
                {
                    "id": str(doc.document_id),
                    "type": doc.document_type,
                    "source": doc.source_type,
                    "relevance_score": score
                }
                for doc, score in zip(relevant_docs, retrieval_result.relevance_scores[:len(relevant_docs)])
            ],
            "total_selected": len(relevant_docs)
        }
    
    async def _extract_specific_information(self, 
                                          step: DocumentPlanStep,
                                          retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Extract specific information with high precision"""
        
        query = step.parameters.get("query", "")
        precision = step.parameters.get("precision", "high")
        target_docs = self._get_target_documents(step, retrieval_result)
        
        extracted_info = []
        
        for doc in target_docs:
            # Extract specific information based on query
            specific_content = self._extract_specific_content(query, doc.content)
            
            if specific_content:
                extracted_info.append({
                    "document_id": str(doc.document_id),
                    "query": query,
                    "extracted_content": specific_content,
                    "precision_level": precision,
                    "metadata": {
                        "document_type": doc.document_type,
                        "source_type": doc.source_type
                    }
                })
        
        return {
            "query": query,
            "precision": precision,
            "extracted_information": extracted_info,
            "total_extractions": len(extracted_info)
        }
    
    async def _generate_focused_answer(self, 
                                     step: DocumentPlanStep,
                                     retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Generate a focused answer acknowledging limitations"""
        
        format_type = step.parameters.get("format", "focused")
        acknowledge_limitations = step.parameters.get("acknowledge_limitations", True)
        
        target_docs = self._get_target_documents(step, retrieval_result)
        
        answer_data = {
            "format": format_type,
            "acknowledge_limitations": acknowledge_limitations,
            "source_documents": len(target_docs),
            "retrieval_grade": retrieval_result.retrieval_grade.value,
            "limitations": retrieval_result.gaps_identified,
            "recommendations": retrieval_result.recommendations,
            "focused_answer": "Focused answer based on available documents"
        }
        
        return answer_data
    
    async def _analyze_document_metadata(self, 
                                       step: DocumentPlanStep,
                                       retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Analyze document metadata for comparative analysis"""
        
        focus = step.parameters.get("focus", "document_types")
        group_by = step.parameters.get("group_by", "source_type")
        target_docs = self._get_target_documents(step, retrieval_result)
        
        metadata_analysis = {
            "focus": focus,
            "group_by": group_by,
            "total_documents": len(target_docs),
            "grouped_metadata": {}
        }
        
        # Group documents by specified field
        groups = {}
        for doc in target_docs:
            group_key = getattr(doc, group_by, "unknown")
            if group_key not in groups:
                groups[group_key] = []
            groups[group_key].append({
                "id": str(doc.document_id),
                "type": doc.document_type,
                "created_at": doc.created_at.isoformat() if doc.created_at else None,
                "domain_id": doc.domain_id
            })
        
        metadata_analysis["grouped_metadata"] = groups
        
        return metadata_analysis
    
    async def _extract_comparative_data(self, 
                                      step: DocumentPlanStep,
                                      retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Extract data for comparison across documents"""
        
        query = step.parameters.get("query", "")
        comparison_fields = step.parameters.get("comparison_fields", ["content"])
        target_docs = self._get_target_documents(step, retrieval_result)
        
        comparative_data = {
            "query": query,
            "comparison_fields": comparison_fields,
            "documents": []
        }
        
        for doc in target_docs:
            doc_data = {
                "id": str(doc.document_id),
                "type": doc.document_type,
                "source": doc.source_type,
                "comparison_data": {}
            }
            
            for field in comparison_fields:
                if field == "content":
                    doc_data["comparison_data"]["content"] = doc.content[:1000]
                elif field == "metadata":
                    doc_data["comparison_data"]["metadata"] = {
                        "created_at": doc.created_at.isoformat() if doc.created_at else None,
                        "domain_id": doc.domain_id,
                        "created_by": doc.created_by
                    }
            
            comparative_data["documents"].append(doc_data)
        
        return comparative_data
    
    async def _perform_comparison(self, 
                                step: DocumentPlanStep,
                                retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Perform detailed comparison across documents"""
        
        comparison_type = step.parameters.get("comparison_type", "cross_document")
        format_type = step.parameters.get("format", "structured")
        target_docs = self._get_target_documents(step, retrieval_result)
        
        comparison_result = {
            "comparison_type": comparison_type,
            "format": format_type,
            "documents_compared": len(target_docs),
            "comparison_analysis": {
                "similarities": [],
                "differences": [],
                "unique_content": []
            }
        }
        
        # Simple comparison logic - could be enhanced with more sophisticated analysis
        if len(target_docs) >= 2:
            doc1, doc2 = target_docs[0], target_docs[1]
            
            # Find similarities
            similarities = self._find_similarities(doc1.content, doc2.content)
            comparison_result["comparison_analysis"]["similarities"] = similarities
            
            # Find differences
            differences = self._find_differences(doc1.content, doc2.content)
            comparison_result["comparison_analysis"]["differences"] = differences
        
        return comparison_result
    
    async def _synthesize_comparative_answer(self, 
                                           step: DocumentPlanStep,
                                           retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Synthesize comparative answer highlighting key differences"""
        
        format_type = step.parameters.get("format", "comparative")
        highlight_differences = step.parameters.get("highlight_differences", True)
        
        return {
            "format": format_type,
            "highlight_differences": highlight_differences,
            "comparative_answer": "Comparative analysis highlighting key differences and similarities",
            "key_differences": retrieval_result.gaps_identified,
            "recommendations": retrieval_result.recommendations
        }
    
    async def _identify_structured_content(self, 
                                         step: DocumentPlanStep,
                                         retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Identify structured content in documents"""
        
        content_types = step.parameters.get("content_types", ["tables", "lists", "key_value_pairs"])
        target_docs = self._get_target_documents(step, retrieval_result)
        
        structured_content = {
            "content_types": content_types,
            "documents": []
        }
        
        for doc in target_docs:
            doc_structured = {
                "id": str(doc.document_id),
                "type": doc.document_type,
                "structured_elements": []
            }
            
            # Simple structured content detection
            if "table" in content_types and self._has_table_content(doc.content):
                doc_structured["structured_elements"].append("table")
            
            if "list" in content_types and self._has_list_content(doc.content):
                doc_structured["structured_elements"].append("list")
            
            if "key_value_pairs" in content_types and self._has_key_value_content(doc.content):
                doc_structured["structured_elements"].append("key_value_pairs")
            
            structured_content["documents"].append(doc_structured)
        
        return structured_content
    
    async def _extract_structured_data(self, 
                                     step: DocumentPlanStep,
                                     retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Extract structured data relevant to question"""
        
        query = step.parameters.get("query", "")
        preserve_structure = step.parameters.get("preserve_structure", True)
        target_docs = self._get_target_documents(step, retrieval_result)
        
        structured_data = {
            "query": query,
            "preserve_structure": preserve_structure,
            "extracted_data": []
        }
        
        for doc in target_docs:
            # Extract structured data based on query
            extracted = self._extract_structured_from_content(query, doc.content)
            if extracted:
                structured_data["extracted_data"].append({
                    "document_id": str(doc.document_id),
                    "data": extracted
                })
        
        return structured_data
    
    async def _format_structured_answer(self, 
                                      step: DocumentPlanStep,
                                      retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Format answer as structured data"""
        
        format_type = step.parameters.get("format", "structured")
        include_metadata = step.parameters.get("include_metadata", True)
        
        return {
            "format": format_type,
            "include_metadata": include_metadata,
            "structured_answer": "Structured answer with metadata",
            "data_sources": len(retrieval_result.documents)
        }
    
    async def _summarize_document_content(self, 
                                        step: DocumentPlanStep,
                                        retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Summarize document content relevant to question"""
        
        max_length = step.parameters.get("max_length", 500)
        focus = step.parameters.get("focus", "")
        target_docs = self._get_target_documents(step, retrieval_result)
        
        summaries = []
        
        for doc in target_docs:
            summary = self._create_document_summary(doc.content, focus, max_length)
            summaries.append({
                "document_id": str(doc.document_id),
                "type": doc.document_type,
                "summary": summary,
                "original_length": len(doc.content)
            })
        
        return {
            "max_length": max_length,
            "focus": focus,
            "summaries": summaries,
            "total_documents": len(summaries)
        }
    
    async def _generate_answer(self, 
                             step: DocumentPlanStep,
                             retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Generate narrative answer from document summaries"""
        
        format_type = step.parameters.get("format", "narrative")
        include_sources = step.parameters.get("include_sources", True)
        
        return {
            "format": format_type,
            "include_sources": include_sources,
            "narrative_answer": "Narrative answer based on document analysis",
            "source_count": len(retrieval_result.documents)
        }
    
    async def _analyze_documents(self, 
                               step: DocumentPlanStep,
                               retrieval_result: DocumentRetrievalResult) -> Dict[str, Any]:
        """Default document analysis function"""
        
        target_docs = self._get_target_documents(step, retrieval_result)
        
        return {
            "analysis_type": "general_document_analysis",
            "documents_analyzed": len(target_docs),
            "retrieval_grade": retrieval_result.retrieval_grade.value,
            "analysis_results": "General analysis completed"
        }
    
    # Helper methods
    
    def _get_target_documents(self, 
                            step: DocumentPlanStep,
                            retrieval_result: DocumentRetrievalResult) -> List[Document]:
        """Get target documents for a step"""
        
        if not step.target_documents:
            return retrieval_result.documents
        
        # Filter documents by target IDs
        target_docs = []
        target_ids = set(step.target_documents)
        
        for doc in retrieval_result.documents:
            if str(doc.document_id) in target_ids:
                target_docs.append(doc)
        
        return target_docs
    
    def _extract_key_insights(self, content: str) -> List[str]:
        """Extract key insights from document content"""
        # Simple key insight extraction - could be enhanced with NLP
        sentences = content.split('.')
        insights = []
        
        for sentence in sentences[:10]:  # Limit to first 10 sentences
            sentence = sentence.strip()
            if len(sentence) > 20 and any(keyword in sentence.lower() for keyword in 
                                        ['important', 'key', 'significant', 'notable', 'critical']):
                insights.append(sentence)
        
        return insights[:5]  # Return top 5 insights
    
    def _calculate_relevance_score(self, query: str, content: str) -> float:
        """Calculate relevance score between query and content"""
        query_words = set(query.lower().split())
        content_words = set(content.lower().split())
        
        if not query_words or not content_words:
            return 0.0
        
        intersection = len(query_words.intersection(content_words))
        union = len(query_words.union(content_words))
        
        return intersection / union if union > 0 else 0.0
    
    def _extract_relevant_snippet(self, query: str, content: str, max_length: int = 200) -> str:
        """Extract relevant snippet from content"""
        # Find sentences containing query words
        sentences = content.split('.')
        relevant_sentences = []
        
        query_words = set(query.lower().split())
        
        for sentence in sentences:
            sentence_words = set(sentence.lower().split())
            if query_words.intersection(sentence_words):
                relevant_sentences.append(sentence.strip())
        
        # Join and truncate
        snippet = '. '.join(relevant_sentences[:3])
        if len(snippet) > max_length:
            snippet = snippet[:max_length] + "..."
        
        return snippet
    
    def _extract_specific_content(self, query: str, content: str) -> str:
        """Extract specific content based on query"""
        # Simple extraction - look for sentences containing query words
        sentences = content.split('.')
        relevant_sentences = []
        
        query_words = set(query.lower().split())
        
        for sentence in sentences:
            sentence_words = set(sentence.lower().split())
            if query_words.intersection(sentence_words):
                relevant_sentences.append(sentence.strip())
        
        return '. '.join(relevant_sentences[:2])  # Return top 2 relevant sentences
    
    def _find_similarities(self, content1: str, content2: str) -> List[str]:
        """Find similarities between two documents"""
        # Simple similarity detection
        words1 = set(content1.lower().split())
        words2 = set(content2.lower().split())
        
        common_words = words1.intersection(words2)
        return list(common_words)[:10]  # Return top 10 common words
    
    def _find_differences(self, content1: str, content2: str) -> List[str]:
        """Find differences between two documents"""
        # Simple difference detection
        words1 = set(content1.lower().split())
        words2 = set(content2.lower().split())
        
        unique_to_1 = words1 - words2
        unique_to_2 = words2 - words1
        
        return {
            "unique_to_first": list(unique_to_1)[:5],
            "unique_to_second": list(unique_to_2)[:5]
        }
    
    def _has_table_content(self, content: str) -> bool:
        """Check if content has table-like structure"""
        return '|' in content or '\t' in content or '  ' in content
    
    def _has_list_content(self, content: str) -> bool:
        """Check if content has list-like structure"""
        lines = content.split('\n')
        list_indicators = sum(1 for line in lines if line.strip().startswith(('-', '*', '•', '1.', '2.')))
        return list_indicators > 2
    
    def _has_key_value_content(self, content: str) -> bool:
        """Check if content has key-value pair structure"""
        lines = content.split('\n')
        kv_indicators = sum(1 for line in lines if ':' in line and len(line.split(':')) == 2)
        return kv_indicators > 2
    
    def _extract_structured_from_content(self, query: str, content: str) -> Dict[str, Any]:
        """Extract structured data from content based on query"""
        # Simple structured extraction
        return {
            "query": query,
            "extracted_data": "Structured data extracted from content",
            "confidence": 0.8
        }
    
    def _create_document_summary(self, content: str, focus: str, max_length: int) -> str:
        """Create a summary of document content"""
        # Simple summarization - take first few sentences
        sentences = content.split('.')
        summary_sentences = []
        
        for sentence in sentences:
            if len('. '.join(summary_sentences)) + len(sentence) < max_length:
                summary_sentences.append(sentence.strip())
            else:
                break
        
        summary = '. '.join(summary_sentences)
        if len(summary) > max_length:
            summary = summary[:max_length] + "..."
        
        return summary
    
    def _serialize_analysis_result(self, result: DocumentAnalysisResult) -> Dict[str, Any]:
        """Serialize analysis result for JSON output"""
        return {
            "document_id": result.document_id,
            "analysis_type": result.analysis_type,
            "content": result.content,
            "metadata": result.metadata,
            "confidence": result.confidence,
            "key_insights": result.key_insights,
            "structured_data": result.structured_data
        }
    
    async def _generate_final_answer(self, 
                                   plan: DocumentPlan,
                                   step_results: List[ExecutionResult]) -> str:
        """Generate final answer from step results"""
        
        # Simple final answer generation
        if not step_results:
            return "No analysis results available."
        
        # Get the last successful result
        last_result = None
        for result in reversed(step_results):
            if result.success:
                last_result = result
                break
        
        if not last_result:
            return "Analysis failed - no successful steps completed."
        
        # Generate answer based on plan strategy
        if plan.strategy == DocumentPlanningStrategy.COMPREHENSIVE_ANALYSIS:
            return f"Based on comprehensive analysis of {len(plan.retrieval_result.documents)} documents, here's what I found..."
        elif plan.strategy == DocumentPlanningStrategy.COMPARATIVE_ANALYSIS:
            return f"After comparing {len(plan.retrieval_result.documents)} documents, here are the key differences and similarities..."
        elif plan.strategy == DocumentPlanningStrategy.STRUCTURED_EXTRACTION:
            return f"Here's the structured data extracted from {len(plan.retrieval_result.documents)} documents..."
        else:
            return f"Based on analysis of {len(plan.retrieval_result.documents)} documents, here's the answer to your question..."

# Example usage
async def test_document_executor():
    """Test the document plan executor"""
    
    # Create mock services
    executor = DocumentPlanExecutor()
    
    # Create a mock plan
    from .enhanced_document_planner import DocumentPlan, DocumentPlanStep, DocumentPlanningStrategy, DocumentRetrievalResult, RetrievalGrade
    
    mock_retrieval = DocumentRetrievalResult(
        documents=[],  # Mock documents would go here
        insights=[],
        retrieval_grade=RetrievalGrade.GOOD,
        relevance_scores=[0.8, 0.7, 0.6],
        coverage_analysis={"total_docs": 3, "coverage_score": 0.8},
        gaps_identified=[],
        recommendations=[]
    )
    
    mock_plan = DocumentPlan(
        original_question="What are the key financial metrics?",
        reframed_question="What are the key financial metrics mentioned in the documents?",
        strategy=DocumentPlanningStrategy.COMPREHENSIVE_ANALYSIS,
        confidence=0.8,
        steps=[
            DocumentPlanStep(
                step_number=1,
                action="analyze_document_content",
                parameters={"focus": "financial_metrics"},
                reasoning="Analyze documents for financial metrics",
                target_documents=[],
                expected_output="Financial metrics analysis"
            )
        ],
        retrieval_result=mock_retrieval
    )
    
    try:
        results = await executor.execute_plan(mock_plan)
        print(f"Execution successful: {results['execution_successful']}")
        print(f"Final answer: {results['final_answer']}")
        
    except Exception as e:
        print(f"Error testing executor: {e}")

if __name__ == "__main__":
    import asyncio
    asyncio.run(test_document_executor())
